// Generated by CIRCT firtool-1.135.0
module ADPCM(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:45:7
  input  [3:0]  io_data,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:55:14
  input  [16:0] io_in_step,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:55:14
  input  [16:0] io_in_sample,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:55:14
  output [16:0] io_out_step,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:55:14
  output [16:0] io_out_sample	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:55:14
);

  reg  [10:0] casez_tmp;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
  always @(*) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
    casez (io_data[2:0])	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
      3'b000:
        casez_tmp = 11'hE6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
      3'b001:
        casez_tmp = 11'hE6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
      3'b010:
        casez_tmp = 11'hE6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
      3'b011:
        casez_tmp = 11'hE6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
      3'b100:
        casez_tmp = 11'h133;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
      3'b101:
        casez_tmp = 11'h199;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
      3'b110:
        casez_tmp = 11'h200;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
      default:
        casez_tmp = 11'h266;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
    endcase	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
  end // always @(*)
  wire [27:0] _step_T_1 =
    28'({{11{io_in_step[16]}}, io_in_step} * {{17{casez_tmp[10]}}, casez_tmp});	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27
  wire [19:0] _io_out_step_T_1 =
    $signed(_step_T_1[27:8]) < 20'sh7F ? 20'h7F : _step_T_1[27:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:264:51, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:{27,48}
  reg  [4:0]  casez_tmp_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
  always @(*) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
    casez (io_data)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b0000:
        casez_tmp_0 = 5'h1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b0001:
        casez_tmp_0 = 5'h3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b0010:
        casez_tmp_0 = 5'h5;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b0011:
        casez_tmp_0 = 5'h7;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b0100:
        casez_tmp_0 = 5'h9;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b0101:
        casez_tmp_0 = 5'hB;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b0110:
        casez_tmp_0 = 5'hD;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b0111:
        casez_tmp_0 = 5'hF;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b1000:
        casez_tmp_0 = 5'h1F;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b1001:
        casez_tmp_0 = 5'h1D;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b1010:
        casez_tmp_0 = 5'h1B;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b1011:
        casez_tmp_0 = 5'h19;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b1100:
        casez_tmp_0 = 5'h17;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b1101:
        casez_tmp_0 = 5'h15;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      4'b1110:
        casez_tmp_0 = 5'h13;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
      default:
        casez_tmp_0 = 5'h11;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
    endcase	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:28
  end // always @(*)
  wire [21:0] _delta_T =
    22'({{5{io_in_step[16]}}, io_in_step} * {{17{casez_tmp_0[4]}}, casez_tmp_0});	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:75:27, :79:28
  wire [19:0] _io_out_sample_T =
    20'({{3{io_in_sample[16]}}, io_in_sample} + {_delta_T[21], _delta_T[21:3]});	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:79:{28,50}, :80:44
  wire [19:0] _io_out_sample_T_2 =
    $signed(_io_out_sample_T) < -20'sh8000 ? 20'hF8000 : _io_out_sample_T;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:264:51, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:80:44
  assign io_out_step =
    $signed(_io_out_step_T_1) < 20'sh6000 ? _io_out_step_T_1[16:0] : 17'h6000;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:264:{51,60}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:45:7
  assign io_out_sample =
    $signed(_io_out_sample_T_2) < 20'sh7FFF ? _io_out_sample_T_2[16:0] : 17'h7FFF;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:264:{51,60}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/ymz/ADPCM.scala:45:7
endmodule

