// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module AsyncMemArbiter(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
  input         io_in_0_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input         io_in_0_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input  [6:0]  io_in_0_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input  [15:0] io_in_0_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output [15:0] io_in_0_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output        io_in_0_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output        io_in_0_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input         io_in_1_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input         io_in_1_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input  [6:0]  io_in_1_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input  [15:0] io_in_1_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output [15:0] io_in_1_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output        io_in_1_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output        io_in_1_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output        io_out_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output        io_out_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output [6:0]  io_out_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  output [15:0] io_out_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input  [15:0] io_out_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input         io_out_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
  input         io_out_valid	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:47:14
);

  reg         busyReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:73:24
  reg  [1:0]  indexReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:74:25
  wire [1:0]  index_enc =
    io_in_0_rd | io_in_0_wr ? 2'h1 : {io_in_1_rd | io_in_1_wr, 1'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7, :77:65, src/main/scala/chisel3/util/Mux.scala:58:84
  wire [1:0]  chosen = busyReg ? indexReg : index_enc;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:73:24, :74:25, :80:19, src/main/scala/chisel3/util/Mux.scala:58:84
  wire        io_out_rd_0 = chosen[0] & io_in_0_rd | chosen[1] & io_in_1_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:356:20, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:80:19
  wire [6:0]  _io_out_mem_addr_T = chosen[0] ? io_in_0_addr : 7'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:358:22, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:80:19
  wire [6:0]  _io_out_mem_addr_T_1 = chosen[1] ? io_in_1_addr : 7'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:358:22, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:80:19
  wire [15:0] _io_out_mem_din_T = chosen[0] ? io_in_0_din : 16'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:360:21, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:80:19
  wire [15:0] _io_out_mem_din_T_1 = chosen[1] ? io_in_1_din : 16'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:360:21, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:80:19
  wire        _io_out_io_in_1_wait_n_T = chosen == 2'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:354:45, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:80:19
  wire        effectiveRequest = ~busyReg & io_out_rd_0 & io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:356:20, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:73:24, :83:{26,35,48}
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
      busyReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7, :73:24
      indexReg <= 2'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:74:25
    end
    else begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
      busyReg <= ~io_out_valid & (effectiveRequest | busyReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:73:24, :83:{35,48}, :86:22, :87:13, :88:32, :89:13
      if (io_out_valid | ~effectiveRequest) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:74:25, :83:{35,48}, :86:22, :88:32
      end
      else	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:74:25, :86:22, :88:32
        indexReg <= index_enc;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:74:25, src/main/scala/chisel3/util/Mux.scala:58:84
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
        busyReg = _RANDOM[/*Zero width*/ 1'b0][0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7, :73:24
        indexReg = _RANDOM[/*Zero width*/ 1'b0][2:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7, :73:24, :74:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_0_dout = io_out_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
  assign io_in_0_wait_n = (_io_out_io_in_1_wait_n_T | chosen[0]) & io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:354:45, :362:{36,49}, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7, :80:19
  assign io_in_0_valid = chosen[0] & io_out_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:363:30, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7, :80:19
  assign io_in_1_dout = io_out_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
  assign io_in_1_wait_n = (_io_out_io_in_1_wait_n_T | chosen[1]) & io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:354:45, :362:{36,49}, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7, :80:19
  assign io_in_1_valid = chosen[1] & io_out_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:363:30, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7, :80:19
  assign io_out_rd = io_out_rd_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:356:20, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
  assign io_out_wr = chosen[0] & io_in_0_wr | chosen[1] & io_in_1_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:357:20, :385:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7, :80:19
  assign io_out_addr = _io_out_mem_addr_T | _io_out_mem_addr_T_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:358:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
  assign io_out_din = _io_out_mem_din_T | _io_out_mem_din_T_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:360:21, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncMemArbiter.scala:46:7
endmodule

