// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BurstWriteDMA(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
  input         io_start,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:50:14
  output        io_out_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:50:14
  output [31:0] io_out_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:50:14
  output [63:0] io_out_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:50:14
  input         io_out_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:50:14
  input         io_out_burstDone	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:50:14
);

  wire        _fifo_io_enq_ready;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:70:20
  wire [6:0]  _fifo_io_count;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:70:20
  reg         readEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:62:30
  reg         writeEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:63:31
  reg         readPendingReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:64:31
  reg         writePendingReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:65:32
  wire        start = io_start & ~(readEnableReg | writeEnableReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:62:30, :63:31, :75:28, :76:{24,27}
  wire        write = writeEnableReg & (writePendingReg | _fifo_io_count == 7'h40);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:63:31, :65:32, :70:20, :72:38, :78:{30,50}
  wire        effectiveWrite = write & io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:78:30, :80:30
  reg  [14:0] wordCounter;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
  reg  [8:0]  burstCounter;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
  wire        read =
    readEnableReg & (~readPendingReg & _fifo_io_enq_ready | _fifo_io_count < 7'h3F);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:62:30, :64:31, :70:20, :71:38, :77:{28,33,49,71,90}
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
      readEnableReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :62:30
      writeEnableReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :63:31
      readPendingReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :64:31
      writePendingReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :65:32
      wordCounter <= 15'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
      burstCounter <= 9'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
    end
    else begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
      readEnableReg <= start | ~(read & (&wordCounter)) & readEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:62:30, :76:24, :77:28, :102:{15,31,69,85}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, :45:24, :85:24, :86:{48,55}
      writeEnableReg <= start | ~(io_out_burstDone & (&burstCounter)) & writeEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:63:31, :76:24, :103:{15,32,71,88}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, :45:24, :85:24, :86:{48,55}
      readPendingReg <= read;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:64:31, :77:28
      writePendingReg <= ~io_out_burstDone & (effectiveWrite | writePendingReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:65:32, :80:30, :113:26, :114:21, :115:30, :116:21
      if (read)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:77:28
        wordCounter <= 15'(wordCounter + 15'h1);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, :46:22
      if (io_out_burstDone)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:50:14
        burstCounter <= 9'(burstCounter + 9'h1);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, :46:22
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
        readEnableReg = _RANDOM[/*Zero width*/ 1'b0][0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :62:30
        writeEnableReg = _RANDOM[/*Zero width*/ 1'b0][1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :62:30, :63:31
        readPendingReg = _RANDOM[/*Zero width*/ 1'b0][2];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :62:30, :64:31
        writePendingReg = _RANDOM[/*Zero width*/ 1'b0][3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :62:30, :65:32
        wordCounter = _RANDOM[/*Zero width*/ 1'b0][18:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :62:30, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
        burstCounter = _RANDOM[/*Zero width*/ 1'b0][27:19];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :62:30, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  Queue64_UInt64 fifo (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:70:20
    .clock        (clock),
    .reset        (reset),
    .io_enq_ready (_fifo_io_enq_ready),
    .io_enq_valid (readPendingReg),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:64:31
    .io_deq_ready (effectiveWrite),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:80:30
    .io_deq_bits  (io_out_din),
    .io_count     (_fifo_io_count),
    .io_flush     (start)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:76:24
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:70:20
  assign io_out_wr = write;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :78:30
  assign io_out_addr = {14'h0, burstCounter, 9'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/dma/BurstWriteDMA.scala:46:7, :135:15, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
endmodule

