// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BurstMemArbiter_2(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
  input         io_in_0_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input  [31:0] io_in_0_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output [63:0] io_in_0_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output        io_in_0_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output        io_in_0_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output        io_in_0_burstDone,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input         io_in_1_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input  [31:0] io_in_1_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input  [63:0] io_in_1_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output        io_in_1_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output        io_in_1_burstDone,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input         io_in_2_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input  [31:0] io_in_2_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input  [7:0]  io_in_2_mask,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input  [63:0] io_in_2_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output        io_in_2_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output        io_out_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output        io_out_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output [31:0] io_out_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output [7:0]  io_out_mask,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output [63:0] io_out_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input  [63:0] io_out_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input         io_out_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input         io_out_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  output [7:0]  io_out_burstLength,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
  input         io_out_burstDone	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:47:14
);

  reg         busyReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:73:24
  reg  [2:0]  indexReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:74:25
  wire [2:0]  _index_enc_T_1 = io_in_1_wr ? 3'h2 : {io_in_2_wr, 2'h0};	// src/main/scala/chisel3/util/Mux.scala:58:84
  wire [2:0]  index_enc = io_in_0_rd ? 3'h1 : _index_enc_T_1;	// src/main/scala/chisel3/util/Mux.scala:58:84
  wire [2:0]  chosen = busyReg ? indexReg : index_enc;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:73:24, :74:25, :80:19, src/main/scala/chisel3/util/Mux.scala:58:84
  wire        io_out_rd_0 = chosen[0] & io_in_0_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:318:20, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:80:19
  wire        io_out_wr_0 = chosen[1] & io_in_1_wr | chosen[2] & io_in_2_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:319:20, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:80:19
  wire [31:0] _io_out_mem_addr_T = chosen[0] ? io_in_0_addr : 32'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:321:22, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:80:19
  wire [31:0] _io_out_mem_addr_T_1 = chosen[1] ? io_in_1_addr : 32'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:321:22, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:80:19
  wire [31:0] _io_out_mem_addr_T_2 = chosen[2] ? io_in_2_addr : 32'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:321:22, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:80:19
  wire [7:0]  _io_out_mem_mask_T_2 = chosen[2] ? io_in_2_mask : 8'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:322:22, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:80:19
  wire [63:0] _io_out_mem_din_T_1 = chosen[1] ? io_in_1_din : 64'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:323:21, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:80:19
  wire [63:0] _io_out_mem_din_T_2 = chosen[2] ? io_in_2_din : 64'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:323:21, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:80:19
  wire        _io_out_io_in_2_wait_n_T = chosen == 3'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:316:45, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:80:19
  wire        effectiveRequest = ~busyReg & (io_out_rd_0 | io_out_wr_0) & io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:318:20, :319:20, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:73:24, :83:{26,35,49,63}
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
      busyReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :73:24
      indexReg <= 3'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:74:25
    end
    else begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
      busyReg <= ~io_out_burstDone & (effectiveRequest | busyReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:73:24, :83:{35,63}, :86:26, :87:13, :88:32, :89:13
      if (io_out_burstDone | ~effectiveRequest) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:74:25, :83:{35,63}, :86:26, :88:32
      end
      else	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:74:25, :86:26, :88:32
        indexReg <= index_enc;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:74:25, src/main/scala/chisel3/util/Mux.scala:58:84
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
        busyReg = _RANDOM[/*Zero width*/ 1'b0][0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :73:24
        indexReg = _RANDOM[/*Zero width*/ 1'b0][3:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :73:24, :74:25
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_0_dout = io_out_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
  assign io_in_0_wait_n = (_io_out_io_in_2_wait_n_T | chosen[0]) & io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:316:45, :325:{36,49}, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :80:19
  assign io_in_0_valid = chosen[0] & io_out_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:326:30, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :80:19
  assign io_in_0_burstDone = chosen[0] & io_out_burstDone;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:327:34, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :80:19
  assign io_in_1_wait_n = (_io_out_io_in_2_wait_n_T | chosen[1]) & io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:316:45, :325:{36,49}, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :80:19
  assign io_in_1_burstDone = chosen[1] & io_out_burstDone;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:327:34, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :80:19
  assign io_in_2_wait_n = (_io_out_io_in_2_wait_n_T | chosen[2]) & io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:316:45, :325:{36,49}, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :80:19
  assign io_out_rd = io_out_rd_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:318:20, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
  assign io_out_wr = io_out_wr_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:319:20, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
  assign io_out_addr = _io_out_mem_addr_T | _io_out_mem_addr_T_1 | _io_out_mem_addr_T_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:321:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
  assign io_out_mask = {8{chosen[1]}} | _io_out_mem_mask_T_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:322:22, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :80:19
  assign io_out_din = _io_out_mem_din_T_1 | _io_out_mem_din_T_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:323:21, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7
  assign io_out_burstLength =
    {3'h0, chosen[0], 4'h0} | {1'h0, chosen[1], 6'h0} | {7'h0, chosen[2]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/BurstMemIO.scala:320:29, :349:87, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/BurstMemArbiter.scala:46:7, :80:19
endmodule

