// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module CPU_1(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
  output [15:0] io_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
  input  [7:0]  io_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
  output [7:0]  io_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
  output        io_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
  output        io_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
  output        io_rfsh,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
  output        io_mreq,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
  output        io_iorq,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
  input         io_int,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
  input         io_nmi	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:72:14
);

  wire       _cpu_RESET_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  wire       _cpu_CEN;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  wire       _cpu_WAIT_n = 1'h1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7, :101:19
  wire       _cpu_INT_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  wire       _cpu_NMI_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  wire       _cpu_BUSRQ_n = 1'h1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7, :101:19
  wire       _cpu_MREQ_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  wire       _cpu_IORQ_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  wire       _cpu_RD_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  wire       _cpu_WR_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  wire       _cpu_RFSH_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  reg  [2:0] cen_value;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
    if (reset)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
      cen_value <= 3'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
    else	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
      cen_value <= 3'(cen_value + 3'h1);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, :46:22
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
        cen_value = _RANDOM[/*Zero width*/ 1'b0][2:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign _cpu_RESET_n = ~reset;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19, :102:21
  assign _cpu_CEN = &cen_value;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, :45:24
  assign _cpu_INT_n = ~io_int;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19, :106:19
  assign _cpu_NMI_n = ~io_nmi;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19, :107:19
  T80s cpu (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
    .RESET_n (_cpu_RESET_n),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
    .CLK     (clock),
    .CEN     (_cpu_CEN),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
    .WAIT_n  (_cpu_WAIT_n),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
    .INT_n   (_cpu_INT_n),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
    .NMI_n   (_cpu_NMI_n),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
    .BUSRQ_n (_cpu_BUSRQ_n),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
    .M1_n    (/* unused */),
    .MREQ_n  (_cpu_MREQ_n),
    .IORQ_n  (_cpu_IORQ_n),
    .RD_n    (_cpu_RD_n),
    .WR_n    (_cpu_WR_n),
    .RFSH_n  (_cpu_RFSH_n),
    .HALT_n  (/* unused */),
    .BUSAK_n (/* unused */),
    .A       (io_addr),
    .DI      (io_din),
    .DO      (io_dout),
    .REG     (/* unused */)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:101:19
  assign io_rd = ~_cpu_RD_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7, :101:19, :112:12
  assign io_wr = ~_cpu_WR_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7, :101:19, :113:12
  assign io_rfsh = ~_cpu_RFSH_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7, :101:19, :114:14
  assign io_mreq = ~_cpu_MREQ_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7, :101:19, :110:14
  assign io_iorq = ~_cpu_IORQ_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/CPU.scala:71:7, :101:19, :111:14
endmodule

