// Generated by CIRCT firtool-1.135.0
module Crossing(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:45:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:45:7
  input         io_targetClock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:46:14
  input         io_in_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:46:14
  input  [31:0] io_in_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:46:14
  output [63:0] io_in_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:46:14
  output        io_out_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:46:14
  output [31:0] io_out_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:46:14
  input  [63:0] io_out_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:46:14
  input         io_out_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:46:14
  input         io_out_valid	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:46:14
);

  DualClockFIFO addrFifo (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:56:52
    .clock        (io_targetClock),
    .io_readClock (clock),
    .io_deq_ready (io_out_wait_n),
    .io_deq_valid (io_out_rd),
    .io_deq_bits  (io_out_addr),
    .io_enq_valid (io_in_rd),
    .io_enq_bits  (io_in_addr)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:56:52
  DualClockFIFO_1 dataFifo (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:60:43
    .clock        (clock),
    .io_readClock (io_targetClock),
    .io_deq_bits  (io_in_dout),
    .io_enq_valid (io_out_valid),
    .io_enq_bits  (io_out_dout)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:60:43
endmodule

