// Generated by CIRCT firtool-1.135.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module DataFreezer(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
  input         io_targetClock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  input         io_in_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  input         io_in_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  input  [6:0]  io_in_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  input  [15:0] io_in_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  output [15:0] io_in_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  output        io_in_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  output        io_in_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  output        io_out_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  output        io_out_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  output [6:0]  io_out_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  output [15:0] io_out_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  input  [15:0] io_out_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  input         io_out_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
  input         io_out_valid	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
);

  reg         clear_s;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:242:26
  reg         clear_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:40
  wire        clear = clear_s ^ clear_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:{31,40}, :242:26
  reg         wait_n_enableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:188:28
  wire        wait_n = io_out_wait_n | wait_n_enableReg & ~clear;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, :188:28, :190:{7,21,24}
  reg         valid_enableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:188:28
  wire        valid = io_out_valid | valid_enableReg & ~clear;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, :188:28, :190:{7,21,24}
  reg  [15:0] data_dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:203:28
  reg         data_enableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:204:28
  reg         pendingRead;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:170:28
  reg         pendingWrite;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:171:29
  reg         clearRead_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:174:35
  wire        clearRead = clear & clearRead_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:174:{25,35}
  wire        io_out_rd_0 = io_in_rd & (~pendingRead | clearRead);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:170:28, :174:25, :186:{25,29,42}
  wire        io_out_wr_0 = io_in_wr & (~pendingWrite | clear);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:171:29, :187:{25,29,43}
  `ifndef SYNTHESIS	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:189:9
    always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:189:9
      if ((`PRINTF_COND_) & ~reset)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:189:9
        $fwrite(32'h80000002,
                "DataFreezer(read: %d, write: %d, wait: %d, valid: %d, clear: %d)\n",
                io_out_rd_0, io_out_wr_0, wait_n, valid, clear);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, :190:7, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:186:25, :187:25, :189:9
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge io_targetClock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
    if (reset)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
      clear_s <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
    else	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
      clear_s <= ~clear_s;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:242:26, :243:31
  end // always @(posedge)
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
    clear_REG <= clear_s;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:40, :242:26
    if (io_out_valid)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:150:14
      data_dataReg <= io_out_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:203:28
    clearRead_REG <= valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:190:7, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:174:35
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
      wait_n_enableReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:188:28, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
      valid_enableReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:188:28, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
      data_enableReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:204:28, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
      pendingRead <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7, :170:28
      pendingWrite <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7, :171:29
    end
    else begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
      wait_n_enableReg <= io_out_wait_n | ~clear & wait_n_enableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, :188:28, :189:{13,25,53,65}
      valid_enableReg <= io_out_valid | ~clear & valid_enableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, :188:28, :189:{13,25,53,65}
      data_enableReg <= ~clear & (io_out_valid | data_enableReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, :188:28, :189:{53,65}, :204:28, :205:{17,29,54,66}
      pendingRead <= io_in_rd & io_out_wait_n | ~clearRead & pendingRead;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:170:28, :172:32, :174:25, :176:{23,37,69,83}
      pendingWrite <= io_in_wr & io_out_wait_n | ~clear & pendingWrite;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, :188:28, :189:{53,65}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:171:29, :173:33, :177:{24,39,72,87}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
        clear_s = _RANDOM[/*Zero width*/ 1'b0][0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
        clear_REG = _RANDOM[/*Zero width*/ 1'b0][1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:40, :242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
        wait_n_enableReg = _RANDOM[/*Zero width*/ 1'b0][2];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:188:28, :242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
        valid_enableReg = _RANDOM[/*Zero width*/ 1'b0][3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:188:28, :242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
        data_dataReg = _RANDOM[/*Zero width*/ 1'b0][19:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:203:28, :242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
        data_enableReg = _RANDOM[/*Zero width*/ 1'b0][20];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:204:28, :242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
        pendingRead = _RANDOM[/*Zero width*/ 1'b0][21];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7, :170:28
        pendingWrite = _RANDOM[/*Zero width*/ 1'b0][22];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7, :171:29
        clearRead_REG = _RANDOM[/*Zero width*/ 1'b0][23];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:242:26, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7, :174:35
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_dout = data_enableReg & ~clear ? data_dataReg : io_out_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:151:31, :190:24, :203:28, :204:28, :206:{8,19}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
  assign io_in_wait_n = wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:190:7, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
  assign io_in_valid = valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:190:7, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
  assign io_out_rd = io_out_rd_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7, :186:25
  assign io_out_wr = io_out_wr_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7, :187:25
  assign io_out_addr = io_in_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
  assign io_out_din = io_in_din;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/Crossing.scala:149:7
endmodule

