// Generated by CIRCT firtool-1.135.0
module DualClockFIFO_7(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:46:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:46:7
  input         io_readClock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
  input         io_deq_ready,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
  output        io_deq_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
  output [16:0] io_deq_bits_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
  output [31:0] io_deq_bits_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
  output [3:0]  io_deq_bits_mask,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
  input         io_enq_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
  input         io_enq_bits_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
  input  [16:0] io_enq_bits_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
  input  [31:0] io_enq_bits_din	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14
);

  wire        io_enq_ready;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:79:19
  wire [53:0] _fifo_data;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
  wire        _fifo_rdreq;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
  wire        _fifo_wrreq;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
  wire [53:0] _fifo_q;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
  wire        _fifo_rdempty;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
  wire        _fifo_wrfull;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
  assign io_enq_ready = ~_fifo_wrfull;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20, :79:19
  assign _fifo_data = {io_enq_bits_wr, io_enq_bits_addr, io_enq_bits_din, 4'hF};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:47:14, :74:20, :80:31
  assign _fifo_rdreq = io_deq_ready & ~_fifo_rdempty;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20, :85:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  assign _fifo_wrreq = io_enq_ready & io_enq_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20, :79:19, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  dual_clock_fifo #(
    .DATA_WIDTH(54),
    .DEPTH(16)
  ) fifo (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
    .data    (_fifo_data),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
    .rdclk   (io_readClock),
    .rdreq   (_fifo_rdreq),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
    .wrclk   (clock),
    .wrreq   (_fifo_wrreq),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
    .q       (_fifo_q),
    .rdempty (_fifo_rdempty),
    .wrfull  (_fifo_wrfull)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:74:20
  assign io_deq_valid = ~_fifo_rdempty;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:46:7, :74:20, :85:19
  assign io_deq_bits_addr = _fifo_q[52:36];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:46:7, :74:20, :86:36
  assign io_deq_bits_din = _fifo_q[35:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:46:7, :74:20, :86:36
  assign io_deq_bits_mask = _fifo_q[3:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/DualClockFIFO.scala:46:7, :74:20, :86:36
endmodule

