// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module EEPROM(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
  output        io_mem_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  output        io_mem_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  output [6:0]  io_mem_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  output [15:0] io_mem_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  input  [15:0] io_mem_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  input         io_mem_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  input         io_mem_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  input         io_serial_cs,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  input         io_serial_sck,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  input         io_serial_sdi,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
  output        io_serial_sdo	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
);

  reg  [2:0]  stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25
  reg  [16:0] counterReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27
  reg  [5:0]  addrReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20
  reg  [15:0] dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20
  reg  [1:0]  opcodeReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:71:22
  reg         serialReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26
  reg         writeAllReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:73:28
  reg         writeEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:74:31
  reg         sckRising_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:44
  wire        sckRising = io_serial_sck & ~sckRising_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:{33,36,44}
  wire        read = opcodeReg == 2'h2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :71:22, :81:24
  wire        write = opcodeReg == 2'h1 & writeEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :71:22, :74:31, :82:{25,33}
  wire        erase = (&opcodeReg) & writeEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:71:22, :74:31, :83:{25,33}
  wire        _disableWrite_T = opcodeReg == 2'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :71:22, :84:28
  wire        writeAll = _disableWrite_T & addrReg[4:3] == 2'h1 & writeEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :69:20, :74:31, :84:{28,36,46,53,61}
  wire        eraseAll = _disableWrite_T & addrReg[4:3] == 2'h2 & writeEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :69:20, :74:31, :84:{28,46}, :85:{36,53,61}
  wire        _GEN = sckRising & counterReg[0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27, :80:24, :90:112, :116:23, :125:20, :126:22
  wire        _GEN_0 = writeAll | eraseAll;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:84:{36,61}, :85:{36,61}, :123:17, :135:32, :137:21, :140:32, :141:21
  wire        _GEN_1 = read | write | erase;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:81:24, :82:33, :83:33, :123:17, :126:22, :130:29, :133:29, :135:32
  reg  [5:0]  casez_tmp;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:98:20, :102:15
  wire [5:0]  _GEN_2 =
    ~(counterReg[0]) | _GEN_1 | ~_GEN_0 ? {addrReg[4:0], io_serial_sdi} : 6'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27, :69:20, :80:24, :123:{17,24}, :125:20, :126:22, :130:29, :133:29, :135:32, :137:21, :140:32, :141:21
  wire [5:0]  _GEN_3 =
    stateReg == 3'h3 | stateReg == 3'h4 | ~(stateReg == 3'h5 & io_mem_wait_n)
      ? addrReg
      : 6'(addrReg + 6'h1);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :69:20, :98:20, :129:22, :134:22, :163:18, :177:27, :178:{17,28}
  always @(*) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :90:18, :98:20, :102:15, :116:23
    casez (stateReg)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :69:20, :90:18, :98:20, :102:15, :116:23
      3'b000:
        casez_tmp = 6'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :90:18, :98:20, :102:15, :116:23
      3'b001:
        casez_tmp = addrReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :90:18, :98:20, :102:15, :116:23
      3'b010:
        casez_tmp = sckRising ? _GEN_2 : addrReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :90:18, :98:20, :102:15, :116:23, :123:17, :125:20, :126:22
      3'b011:
        casez_tmp = addrReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :90:18, :98:20, :102:15, :116:23
      3'b100:
        casez_tmp = addrReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :90:18, :98:20, :102:15, :116:23
      3'b101:
        casez_tmp = _GEN_3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :90:18, :98:20, :102:15, :116:23
      3'b110:
        casez_tmp = _GEN_3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :90:18, :98:20, :102:15, :116:23
      default:
        casez_tmp = _GEN_3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :90:18, :98:20, :102:15, :116:23
    endcase	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :69:20, :90:18, :98:20, :102:15, :116:23
  end // always @(*)
  wire        _GEN_4 = (&stateReg) & sckRising;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :70:20, :90:78, :98:20, :194:23, :195:17
  reg  [15:0] casez_tmp_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:98:20, :103:15
  wire [15:0] _GEN_5 = io_mem_valid ? io_mem_dout : dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :159:26, :160:17
  always @(*) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :90:48, :98:20, :103:15, :159:26, :185:23
    casez (stateReg)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :70:20, :90:48, :98:20, :103:15, :159:26, :185:23
      3'b000:
        casez_tmp_0 = 16'hFFFF;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :90:48, :98:20, :103:15, :159:26, :185:23
      3'b001:
        casez_tmp_0 = dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :90:48, :98:20, :103:15, :159:26, :185:23
      3'b010:
        casez_tmp_0 = dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :90:48, :98:20, :103:15, :159:26, :185:23
      3'b011:
        casez_tmp_0 = _GEN_5;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :90:48, :98:20, :103:15, :159:26, :160:17, :185:23
      3'b100:
        casez_tmp_0 = _GEN_5;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :90:48, :98:20, :103:15, :159:26, :160:17, :185:23
      3'b101:
        casez_tmp_0 = dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :90:48, :98:20, :103:15, :159:26, :185:23
      3'b110:
        casez_tmp_0 = sckRising ? {dataReg[14:0], io_serial_sdi} : dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :90:48, :98:20, :103:15, :159:26, :185:23, :187:17
      default:
        casez_tmp_0 = _GEN_4 ? {dataReg[14:0], 1'h0} : dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :70:20, :90:48, :98:20, :103:15, :159:26, :185:23, :187:17, :194:23, :195:17
    endcase	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :70:20, :90:48, :98:20, :103:15, :159:26, :185:23
  end // always @(*)
  reg         casez_tmp_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :98:20
  wire        _GEN_6 = _GEN_4 ? dataReg[15] : serialReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :72:26, :98:20, :194:23, :195:17, :196:{19,34}
  always @(*) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :90:{18,48}, :98:20, :116:23, :185:23
    casez (stateReg)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :72:26, :90:{18,48}, :98:20, :116:23, :185:23
      3'b000:
        casez_tmp_1 = _GEN_6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :90:{18,48}, :98:20, :116:23, :185:23, :194:23, :196:19
      3'b001:
        casez_tmp_1 = serialReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :90:{18,48}, :98:20, :116:23, :185:23
      3'b010:
        casez_tmp_1 = ~(sckRising & counterReg[0] & read) & serialReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27, :72:26, :80:24, :81:24, :90:{18,48}, :98:20, :116:23, :125:20, :126:22, :128:23, :185:23
      3'b011:
        casez_tmp_1 = serialReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :90:{18,48}, :98:20, :116:23, :185:23
      3'b100:
        casez_tmp_1 = serialReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :90:{18,48}, :98:20, :116:23, :185:23
      3'b101:
        casez_tmp_1 = serialReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :90:{18,48}, :98:20, :116:23, :185:23
      3'b110:
        casez_tmp_1 = ~sckRising & serialReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :90:{18,48}, :98:20, :116:23, :185:23, :186:19
      default:
        casez_tmp_1 = _GEN_6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :90:{18,48}, :98:20, :116:23, :185:23, :194:23, :196:19
    endcase	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :72:26, :90:{18,48}, :98:20, :116:23, :185:23
  end // always @(*)
  reg  [2:0]  casez_tmp_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:98:20, :106:26
  wire [2:0]  _GEN_7 = eraseAll ? 3'h5 : 3'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :85:{36,61}, :134:22, :140:32, :143:22, :144:35
  wire [2:0]  _GEN_8 = writeAll ? 3'h6 : _GEN_7;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:84:{36,61}, :90:48, :135:32, :139:22, :140:32, :143:22, :144:35
  wire [2:0]  _GEN_9 = erase ? 3'h5 : _GEN_8;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:83:33, :133:29, :134:22, :135:32, :139:22, :140:32
  wire [2:0]  _GEN_10 = write ? 3'h6 : _GEN_9;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:82:33, :90:48, :130:29, :132:22, :133:29, :134:22, :135:32
  wire [2:0]  _GEN_11 = read ? 3'h3 : _GEN_10;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:81:24, :126:22, :129:22, :130:29, :132:22, :133:29
  wire [2:0]  _GEN_12 = io_mem_wait_n ? 3'h4 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :95:12, :162:33, :163:18
  always @(*) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:90:{18,48}, :98:20, :106:26, :111:40, :116:23, :159:26, :169:26, :177:27, :185:23
    casez (stateReg)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:{18,48}, :98:20, :106:26, :111:40, :116:23, :159:26, :169:26, :177:27, :185:23
      3'b000:
        casez_tmp_2 = io_serial_cs ? 3'h1 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:{18,48}, :95:12, :98:20, :106:{26,37}, :111:40, :116:23, :159:26, :169:26, :177:27, :185:23
      3'b001:
        casez_tmp_2 = sckRising & io_serial_sdi ? 3'h2 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:{18,48}, :95:12, :98:20, :106:26, :111:{22,40,51}, :116:23, :159:26, :169:26, :177:27, :185:23
      3'b010:
        casez_tmp_2 = _GEN ? _GEN_11 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:{18,48,112}, :95:12, :98:20, :106:26, :111:40, :116:23, :125:20, :126:22, :129:22, :130:29, :159:26, :169:26, :177:27, :185:23
      3'b011:
        casez_tmp_2 = io_mem_valid ? 3'h7 : _GEN_12;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:90:{18,48,78}, :95:12, :98:20, :106:26, :111:40, :116:23, :159:26, :161:18, :162:33, :163:18, :169:26, :177:27, :185:23
      3'b100:
        casez_tmp_2 = io_mem_valid ? 3'h7 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:{18,48,78}, :95:12, :98:20, :106:26, :111:40, :116:23, :159:26, :169:26, :171:18, :177:27, :185:23
      3'b101:
        casez_tmp_2 = io_mem_wait_n & (~writeAllReg | (&addrReg)) ? 3'h0 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :69:20, :73:28, :90:{18,48}, :95:12, :98:20, :106:26, :111:40, :116:23, :159:26, :169:26, :177:27, :179:{14,27,38,44,55}, :185:23
      3'b110:
        casez_tmp_2 = _GEN ? 3'h5 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:{18,48,112}, :95:12, :98:20, :106:26, :111:40, :116:23, :125:20, :126:22, :134:22, :159:26, :169:26, :177:27, :185:23, :188:{20,31}
      default:
        casez_tmp_2 = (&stateReg) & _GEN ? 3'h0 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:{18,48,78,112}, :95:12, :98:20, :106:26, :111:40, :116:23, :125:20, :126:22, :159:26, :169:26, :177:27, :185:23, :194:23, :197:{20,31}
    endcase	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:{18,48}, :98:20, :106:26, :111:40, :116:23, :159:26, :169:26, :177:27, :185:23
  end // always @(*)
  wire [16:0] _GEN_13 = {1'h0, counterReg[16:1]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :68:27, :91:{16,30}
  wire        _io_debug_command_T = stateReg == 3'h2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:18
  wire        _io_debug_idle_T = stateReg == 3'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :98:20
  wire        _GEN_14 = stateReg == 3'h1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :98:20, :106:37
  wire        _GEN_15 = _io_debug_idle_T | _GEN_14;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:71:22, :98:20
  wire        _GEN_16 = _io_debug_command_T & _GEN;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:90:{18,112}, :98:20, :116:23, :125:20, :126:22
  wire        _GEN_17 =
    (_io_debug_command_T | stateReg == 3'h6 | (&stateReg)) & sckRising;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :90:{18,36,48,66,78,98}
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
      stateReg <= 3'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25
      counterReg <= 17'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27
      serialReg <= 1'h1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :72:26
      writeAllReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :73:28
      writeEnableReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :74:31
    end
    else begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
      if (io_serial_cs)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
        stateReg <= casez_tmp_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25, :98:20, :106:26
      else	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:41:14
        stateReg <= 3'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:65:25
      if (_io_debug_idle_T)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:98:20
        counterReg <= 17'h80;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27, :101:18
      else if (_GEN_14 | ~_GEN_16) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:90:112, :98:20, :116:23, :125:20, :126:22
        if (_GEN_17)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:90:98
          counterReg <= _GEN_13;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27, :91:16
      end
      else if (read)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:81:24
        counterReg <= 17'h10000;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27, :127:24
      else if (write | ~(erase | ~writeAll))	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:82:33, :83:33, :84:{36,61}, :90:112, :130:29, :131:24, :133:29, :135:32
        counterReg <= 17'h8000;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27
      else if (_GEN_17)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:90:98
        counterReg <= _GEN_13;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:68:27, :91:16
      serialReg <= _io_debug_idle_T | casez_tmp_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:72:26, :98:20, :104:17
      writeAllReg <=
        ~_io_debug_idle_T & (~_GEN_14 & _GEN_16 & ~_GEN_1 & _GEN_0 | writeAllReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:73:28, :90:112, :98:20, :105:19, :116:23, :123:17, :125:20, :126:22, :130:29, :133:29, :135:32, :137:21, :140:32, :141:21
      if (_GEN_15 | ~_GEN_16 | read | write | erase | _GEN_0) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:71:22, :74:31, :81:24, :82:33, :83:33, :90:112, :98:20, :116:23, :123:17, :125:20, :126:22, :130:29, :133:29, :135:32, :137:21, :140:32, :141:21, :144:35
      end
      else	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:74:31, :98:20, :116:23, :125:20, :126:22, :130:29, :133:29, :135:32, :140:32, :144:35
        writeEnableReg <=
          _disableWrite_T & (&(addrReg[4:3])) | ~(_disableWrite_T & addrReg[4:3] == 2'h0)
          & writeEnableReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :69:20, :74:31, :84:{28,46}, :86:{39,56}, :87:{40,57}, :144:35, :145:28, :147:36, :148:28
    end
    addrReg <= casez_tmp;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :98:20, :102:15
    dataReg <= casez_tmp_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:70:20, :98:20, :103:15
    if (_GEN_15 | ~(_io_debug_command_T & sckRising)) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:71:22, :90:18, :98:20, :116:23, :120:19
    end
    else	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:71:22, :98:20
      opcodeReg <= addrReg[5:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:69:20, :71:22, :120:26
    sckRising_REG <= io_serial_sck;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:44
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
        end	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
        stateReg = _RANDOM[1'h0][2:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :65:25
        counterReg = _RANDOM[1'h0][19:3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :65:25, :68:27
        addrReg = _RANDOM[1'h0][25:20];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :65:25, :69:20
        dataReg = {_RANDOM[1'h0][31:26], _RANDOM[1'h1][9:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :65:25, :70:20
        opcodeReg = _RANDOM[1'h1][11:10];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :70:20, :71:22
        serialReg = _RANDOM[1'h1][12];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :70:20, :72:26
        writeAllReg = _RANDOM[1'h1][13];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :70:20, :73:28
        writeEnableReg = _RANDOM[1'h1][14];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :70:20, :74:31
        sckRising_REG = _RANDOM[1'h1][15];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:44, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :70:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_mem_rd = stateReg == 3'h3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :65:25, :129:22, :207:25
  assign io_mem_wr = stateReg == 3'h5;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :65:25, :134:22, :208:25
  assign io_mem_addr = {addrReg, 1'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :69:20, :209:26
  assign io_mem_din = dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :70:20
  assign io_serial_sdo = serialReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/EEPROM.scala:40:7, :72:26
endmodule

