// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module GPU(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
  input          clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
  input          reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
  input          io_videoClock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_0_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [1:0]   io_layerCtrl_0_format,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_0_regs_tileSize,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_0_regs_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_0_regs_flipX,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_0_regs_flipY,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_0_regs_rowScrollEnable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_0_regs_rowSelectEnable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_layerCtrl_0_regs_scroll_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_layerCtrl_0_regs_scroll_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [11:0]  io_layerCtrl_0_vram8x8_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [31:0]  io_layerCtrl_0_vram8x8_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [9:0]   io_layerCtrl_0_vram16x16_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [31:0]  io_layerCtrl_0_vram16x16_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [8:0]   io_layerCtrl_0_lineRam_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [31:0]  io_layerCtrl_0_lineRam_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output         io_layerCtrl_0_tileRom_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [31:0]  io_layerCtrl_0_tileRom_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [63:0]  io_layerCtrl_0_tileRom_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_1_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [1:0]   io_layerCtrl_1_format,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_1_regs_tileSize,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_1_regs_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_1_regs_flipX,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_1_regs_flipY,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_1_regs_rowScrollEnable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_1_regs_rowSelectEnable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_layerCtrl_1_regs_scroll_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_layerCtrl_1_regs_scroll_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [11:0]  io_layerCtrl_1_vram8x8_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [31:0]  io_layerCtrl_1_vram8x8_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [9:0]   io_layerCtrl_1_vram16x16_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [31:0]  io_layerCtrl_1_vram16x16_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [8:0]   io_layerCtrl_1_lineRam_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [31:0]  io_layerCtrl_1_lineRam_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output         io_layerCtrl_1_tileRom_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [31:0]  io_layerCtrl_1_tileRom_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [63:0]  io_layerCtrl_1_tileRom_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_2_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [1:0]   io_layerCtrl_2_format,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_2_regs_tileSize,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_2_regs_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_2_regs_flipX,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_2_regs_flipY,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_2_regs_rowScrollEnable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_layerCtrl_2_regs_rowSelectEnable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_layerCtrl_2_regs_scroll_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_layerCtrl_2_regs_scroll_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [11:0]  io_layerCtrl_2_vram8x8_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [31:0]  io_layerCtrl_2_vram8x8_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [9:0]   io_layerCtrl_2_vram16x16_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [31:0]  io_layerCtrl_2_vram16x16_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [8:0]   io_layerCtrl_2_lineRam_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [31:0]  io_layerCtrl_2_lineRam_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output         io_layerCtrl_2_tileRom_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [31:0]  io_layerCtrl_2_tileRom_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [63:0]  io_layerCtrl_2_tileRom_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_spriteCtrl_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [1:0]   io_spriteCtrl_format,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_spriteCtrl_start,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_spriteCtrl_zoom,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_spriteCtrl_regs_offset_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_spriteCtrl_regs_offset_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [1:0]   io_spriteCtrl_regs_bank,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_spriteCtrl_regs_fixed,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_spriteCtrl_regs_hFlip,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output         io_spriteCtrl_vram_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [11:0]  io_spriteCtrl_vram_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [127:0] io_spriteCtrl_vram_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output         io_spriteCtrl_tileRom_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [31:0]  io_spriteCtrl_tileRom_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [63:0]  io_spriteCtrl_tileRom_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_spriteCtrl_tileRom_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_spriteCtrl_tileRom_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [7:0]   io_spriteCtrl_tileRom_burstLength,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_spriteCtrl_tileRom_burstDone,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_gameConfig_granularity,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [1:0]   io_gameConfig_layer_0_paletteBank,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [1:0]   io_gameConfig_layer_1_paletteBank,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [1:0]   io_gameConfig_layer_2_paletteBank,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_options_rotate,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_options_flipVideo,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_video_clockEnable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_video_displayEnable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_video_pos_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_video_pos_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_video_vBlank,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_video_regs_size_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [8:0]   io_video_regs_size_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [8:0]   io_spriteLineBuffer_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [15:0]  io_spriteLineBuffer_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output         io_spriteFrameBuffer_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [16:0]  io_spriteFrameBuffer_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [15:0]  io_spriteFrameBuffer_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input          io_spriteFrameBuffer_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output         io_systemFrameBuffer_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [16:0]  io_systemFrameBuffer_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [31:0]  io_systemFrameBuffer_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [14:0]  io_paletteRam_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  input  [15:0]  io_paletteRam_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
  output [23:0]  io_rgb	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
);

  wire [1:0]  _colorMixer_io_spritePen_priority;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28
  wire [5:0]  _colorMixer_io_spritePen_palette;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28
  wire [7:0]  _colorMixer_io_spritePen_color;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28
  wire [15:0] _colorMixer_io_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28
  wire [1:0]  _layerProcessor_2_io_pen_priority;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  wire [5:0]  _layerProcessor_2_io_pen_palette;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  wire [7:0]  _layerProcessor_2_io_pen_color;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  wire [1:0]  _layerProcessor_1_io_pen_priority;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  wire [5:0]  _layerProcessor_1_io_pen_palette;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  wire [7:0]  _layerProcessor_1_io_pen_color;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  wire [1:0]  _layerProcessor_0_io_pen_priority;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  wire [5:0]  _layerProcessor_0_io_pen_palette;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  wire [7:0]  _layerProcessor_0_io_pen_color;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  reg         io_systemFrameBuffer_wr_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:105:39
  reg  [17:0] io_systemFrameBuffer_addr_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:106:41
  reg  [31:0] io_systemFrameBuffer_din_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:108:40
  wire [17:0] _GEN = {9'h0, io_video_pos_x};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:132:20
  wire [17:0] _GEN_0 = {9'h0, io_video_regs_size_y};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:132:20
  wire [17:0] _GEN_1 = {9'h0, 9'(9'(io_video_regs_size_y - io_video_pos_y) - 9'h1)};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:130:{21,29}, :132:30
  wire [17:0] _GEN_2 = {9'h0, 9'(9'(io_video_regs_size_x - io_video_pos_x) - 9'h1)};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:129:{21,29}, :132:40
  wire [17:0] _GEN_3 = {9'h0, io_video_pos_y};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:132:50
  wire [17:0] _GEN_4 = {9'h0, io_video_regs_size_x};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:133:21
  wire [17:0] _io_systemFrameBuffer_addr_T_13 =
    io_options_flipVideo
      ? 18'(18'(_GEN_1 * _GEN_4) + _GEN_2)
      : 18'(18'(_GEN_3 * _GEN_4) + _GEN);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:132:{20,30,40,50}, :133:{10,21,31,40,50}
  wire [17:0] _io_systemFrameBuffer_addr_T_6 =
    io_options_flipVideo
      ? 18'(18'(_GEN * _GEN_0) + _GEN_1)
      : 18'(18'(_GEN_2 * _GEN_0) + _GEN_3);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:132:{10,20,30,40,50}
  always @(posedge io_videoClock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:50:14
    io_systemFrameBuffer_wr_REG <= io_video_clockEnable & io_video_displayEnable;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:105:{39,61}
    io_systemFrameBuffer_addr_REG <=
      io_options_rotate
        ? _io_systemFrameBuffer_addr_T_6
        : _io_systemFrameBuffer_addr_T_13;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:106:41, :131:8, :132:10, :133:10
    io_systemFrameBuffer_din_REG <=
      {8'h0,
       _colorMixer_io_dout[4:0],
       _colorMixer_io_dout[4:2],
       _colorMixer_io_dout[14:10],
       _colorMixer_io_dout[14:12],
       _colorMixer_io_dout[9:5],
       _colorMixer_io_dout[9:7]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28, :108:40, :157:{17,31}, :158:{17,31}, :159:{17,33}, :160:21
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
        end	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
        io_systemFrameBuffer_wr_REG = _RANDOM[1'h0][0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7, :105:39
        io_systemFrameBuffer_addr_REG = _RANDOM[1'h0][18:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7, :105:39, :106:41
        io_systemFrameBuffer_din_REG = {_RANDOM[1'h0][31:19], _RANDOM[1'h1][18:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7, :105:39, :108:40
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  SpriteProcessor spriteProcessor (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:76:31
    .clock                       (clock),
    .reset                       (reset),
    .io_ctrl_enable              (io_spriteCtrl_enable),
    .io_ctrl_format              (io_spriteCtrl_format),
    .io_ctrl_start               (io_spriteCtrl_start),
    .io_ctrl_zoom                (io_spriteCtrl_zoom),
    .io_ctrl_regs_bank           (io_spriteCtrl_regs_bank),
    .io_ctrl_regs_fixed          (io_spriteCtrl_regs_fixed),
    .io_ctrl_regs_hFlip          (io_spriteCtrl_regs_hFlip),
    .io_ctrl_vram_rd             (io_spriteCtrl_vram_rd),
    .io_ctrl_vram_addr           (io_spriteCtrl_vram_addr),
    .io_ctrl_vram_dout           (io_spriteCtrl_vram_dout),
    .io_ctrl_tileRom_rd          (io_spriteCtrl_tileRom_rd),
    .io_ctrl_tileRom_addr        (io_spriteCtrl_tileRom_addr),
    .io_ctrl_tileRom_dout        (io_spriteCtrl_tileRom_dout),
    .io_ctrl_tileRom_wait_n      (io_spriteCtrl_tileRom_wait_n),
    .io_ctrl_tileRom_valid       (io_spriteCtrl_tileRom_valid),
    .io_ctrl_tileRom_burstLength (io_spriteCtrl_tileRom_burstLength),
    .io_ctrl_tileRom_burstDone   (io_spriteCtrl_tileRom_burstDone),
    .io_video_regs_size_x        (io_video_regs_size_x),
    .io_video_regs_size_y        (io_video_regs_size_y),
    .io_frameBuffer_wr           (io_spriteFrameBuffer_wr),
    .io_frameBuffer_addr         (io_spriteFrameBuffer_addr),
    .io_frameBuffer_din          (io_spriteFrameBuffer_din),
    .io_frameBuffer_wait_n       (io_spriteFrameBuffer_wait_n)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:76:31
  LayerProcessor layerProcessor_0 (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .clock                        (io_videoClock),
    .io_ctrl_enable               (io_layerCtrl_0_enable),
    .io_ctrl_format               (io_layerCtrl_0_format),
    .io_ctrl_regs_tileSize        (io_layerCtrl_0_regs_tileSize),
    .io_ctrl_regs_enable          (io_layerCtrl_0_regs_enable),
    .io_ctrl_regs_flipX           (io_layerCtrl_0_regs_flipX),
    .io_ctrl_regs_flipY           (io_layerCtrl_0_regs_flipY),
    .io_ctrl_regs_rowScrollEnable (io_layerCtrl_0_regs_rowScrollEnable),
    .io_ctrl_regs_rowSelectEnable (io_layerCtrl_0_regs_rowSelectEnable),
    .io_ctrl_regs_scroll_x        (io_layerCtrl_0_regs_scroll_x),
    .io_ctrl_regs_scroll_y        (io_layerCtrl_0_regs_scroll_y),
    .io_ctrl_vram8x8_addr         (io_layerCtrl_0_vram8x8_addr),
    .io_ctrl_vram8x8_dout         (io_layerCtrl_0_vram8x8_dout),
    .io_ctrl_vram16x16_addr       (io_layerCtrl_0_vram16x16_addr),
    .io_ctrl_vram16x16_dout       (io_layerCtrl_0_vram16x16_dout),
    .io_ctrl_lineRam_addr         (io_layerCtrl_0_lineRam_addr),
    .io_ctrl_lineRam_dout         (io_layerCtrl_0_lineRam_dout),
    .io_ctrl_tileRom_rd           (io_layerCtrl_0_tileRom_rd),
    .io_ctrl_tileRom_addr         (io_layerCtrl_0_tileRom_addr),
    .io_ctrl_tileRom_dout         (io_layerCtrl_0_tileRom_dout),
    .io_video_clockEnable         (io_video_clockEnable),
    .io_video_pos_x               (io_video_pos_x),
    .io_video_pos_y               (io_video_pos_y),
    .io_video_vBlank              (io_video_vBlank),
    .io_video_regs_size_x         (io_video_regs_size_x),
    .io_video_regs_size_y         (io_video_regs_size_y),
    .io_spriteOffset_x            (io_spriteCtrl_regs_offset_x),
    .io_spriteOffset_y            (io_spriteCtrl_regs_offset_y),
    .io_pen_priority              (_layerProcessor_0_io_pen_priority),
    .io_pen_palette               (_layerProcessor_0_io_pen_palette),
    .io_pen_color                 (_layerProcessor_0_io_pen_color)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  LayerProcessor_1 layerProcessor_1 (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .clock                        (io_videoClock),
    .io_ctrl_enable               (io_layerCtrl_1_enable),
    .io_ctrl_format               (io_layerCtrl_1_format),
    .io_ctrl_regs_tileSize        (io_layerCtrl_1_regs_tileSize),
    .io_ctrl_regs_enable          (io_layerCtrl_1_regs_enable),
    .io_ctrl_regs_flipX           (io_layerCtrl_1_regs_flipX),
    .io_ctrl_regs_flipY           (io_layerCtrl_1_regs_flipY),
    .io_ctrl_regs_rowScrollEnable (io_layerCtrl_1_regs_rowScrollEnable),
    .io_ctrl_regs_rowSelectEnable (io_layerCtrl_1_regs_rowSelectEnable),
    .io_ctrl_regs_scroll_x        (io_layerCtrl_1_regs_scroll_x),
    .io_ctrl_regs_scroll_y        (io_layerCtrl_1_regs_scroll_y),
    .io_ctrl_vram8x8_addr         (io_layerCtrl_1_vram8x8_addr),
    .io_ctrl_vram8x8_dout         (io_layerCtrl_1_vram8x8_dout),
    .io_ctrl_vram16x16_addr       (io_layerCtrl_1_vram16x16_addr),
    .io_ctrl_vram16x16_dout       (io_layerCtrl_1_vram16x16_dout),
    .io_ctrl_lineRam_addr         (io_layerCtrl_1_lineRam_addr),
    .io_ctrl_lineRam_dout         (io_layerCtrl_1_lineRam_dout),
    .io_ctrl_tileRom_rd           (io_layerCtrl_1_tileRom_rd),
    .io_ctrl_tileRom_addr         (io_layerCtrl_1_tileRom_addr),
    .io_ctrl_tileRom_dout         (io_layerCtrl_1_tileRom_dout),
    .io_video_clockEnable         (io_video_clockEnable),
    .io_video_pos_x               (io_video_pos_x),
    .io_video_pos_y               (io_video_pos_y),
    .io_video_vBlank              (io_video_vBlank),
    .io_video_regs_size_x         (io_video_regs_size_x),
    .io_video_regs_size_y         (io_video_regs_size_y),
    .io_spriteOffset_x            (io_spriteCtrl_regs_offset_x),
    .io_spriteOffset_y            (io_spriteCtrl_regs_offset_y),
    .io_pen_priority              (_layerProcessor_1_io_pen_priority),
    .io_pen_palette               (_layerProcessor_1_io_pen_palette),
    .io_pen_color                 (_layerProcessor_1_io_pen_color)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  LayerProcessor_2 layerProcessor_2 (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .clock                        (io_videoClock),
    .io_ctrl_enable               (io_layerCtrl_2_enable),
    .io_ctrl_format               (io_layerCtrl_2_format),
    .io_ctrl_regs_tileSize        (io_layerCtrl_2_regs_tileSize),
    .io_ctrl_regs_enable          (io_layerCtrl_2_regs_enable),
    .io_ctrl_regs_flipX           (io_layerCtrl_2_regs_flipX),
    .io_ctrl_regs_flipY           (io_layerCtrl_2_regs_flipY),
    .io_ctrl_regs_rowScrollEnable (io_layerCtrl_2_regs_rowScrollEnable),
    .io_ctrl_regs_rowSelectEnable (io_layerCtrl_2_regs_rowSelectEnable),
    .io_ctrl_regs_scroll_x        (io_layerCtrl_2_regs_scroll_x),
    .io_ctrl_regs_scroll_y        (io_layerCtrl_2_regs_scroll_y),
    .io_ctrl_vram8x8_addr         (io_layerCtrl_2_vram8x8_addr),
    .io_ctrl_vram8x8_dout         (io_layerCtrl_2_vram8x8_dout),
    .io_ctrl_vram16x16_addr       (io_layerCtrl_2_vram16x16_addr),
    .io_ctrl_vram16x16_dout       (io_layerCtrl_2_vram16x16_dout),
    .io_ctrl_lineRam_addr         (io_layerCtrl_2_lineRam_addr),
    .io_ctrl_lineRam_dout         (io_layerCtrl_2_lineRam_dout),
    .io_ctrl_tileRom_rd           (io_layerCtrl_2_tileRom_rd),
    .io_ctrl_tileRom_addr         (io_layerCtrl_2_tileRom_addr),
    .io_ctrl_tileRom_dout         (io_layerCtrl_2_tileRom_dout),
    .io_video_clockEnable         (io_video_clockEnable),
    .io_video_pos_x               (io_video_pos_x),
    .io_video_pos_y               (io_video_pos_y),
    .io_video_vBlank              (io_video_vBlank),
    .io_video_regs_size_x         (io_video_regs_size_x),
    .io_video_regs_size_y         (io_video_regs_size_y),
    .io_spriteOffset_x            (io_spriteCtrl_regs_offset_x),
    .io_spriteOffset_y            (io_spriteCtrl_regs_offset_y),
    .io_pen_priority              (_layerProcessor_2_io_pen_priority),
    .io_pen_palette               (_layerProcessor_2_io_pen_palette),
    .io_pen_color                 (_layerProcessor_2_io_pen_color)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
  assign _colorMixer_io_spritePen_priority = io_spriteLineBuffer_dout[15:14];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28, :94:65
  assign _colorMixer_io_spritePen_palette = io_spriteLineBuffer_dout[13:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28, :94:65
  assign _colorMixer_io_spritePen_color = io_spriteLineBuffer_dout[7:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28, :94:65
  ColorMixer colorMixer (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28
    .clock                             (io_videoClock),
    .io_gameConfig_granularity         (io_gameConfig_granularity),
    .io_gameConfig_layer_0_paletteBank (io_gameConfig_layer_0_paletteBank),
    .io_gameConfig_layer_1_paletteBank (io_gameConfig_layer_1_paletteBank),
    .io_gameConfig_layer_2_paletteBank (io_gameConfig_layer_2_paletteBank),
    .io_spritePen_priority             (_colorMixer_io_spritePen_priority),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28
    .io_spritePen_palette              (_colorMixer_io_spritePen_palette),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28
    .io_spritePen_color                (_colorMixer_io_spritePen_color),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28
    .io_layer0Pen_priority             (_layerProcessor_0_io_pen_priority),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .io_layer0Pen_palette              (_layerProcessor_0_io_pen_palette),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .io_layer0Pen_color                (_layerProcessor_0_io_pen_color),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .io_layer1Pen_priority             (_layerProcessor_1_io_pen_priority),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .io_layer1Pen_palette              (_layerProcessor_1_io_pen_palette),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .io_layer1Pen_color                (_layerProcessor_1_io_pen_color),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .io_layer2Pen_priority             (_layerProcessor_2_io_pen_priority),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .io_layer2Pen_palette              (_layerProcessor_2_io_pen_palette),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .io_layer2Pen_color                (_layerProcessor_2_io_pen_color),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:84:21
    .io_paletteRam_addr                (io_paletteRam_addr),
    .io_paletteRam_dout                (io_paletteRam_dout),
    .io_dout                           (_colorMixer_io_dout)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:92:28
  assign io_spriteLineBuffer_addr = io_video_pos_x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7
  assign io_systemFrameBuffer_wr = io_systemFrameBuffer_wr_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7, :105:39
  assign io_systemFrameBuffer_addr = io_systemFrameBuffer_addr_REG[16:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7, :106:{31,41}
  assign io_systemFrameBuffer_din = io_systemFrameBuffer_din_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7, :108:40
  assign io_rgb =
    {_colorMixer_io_dout[9:5],
     _colorMixer_io_dout[9:7],
     _colorMixer_io_dout[14:10],
     _colorMixer_io_dout[14:12],
     _colorMixer_io_dout[4:0],
     _colorMixer_io_dout[4:2]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/GPU.scala:49:7, :92:28, :147:12, :157:{17,31}, :158:{17,31}, :159:{17,33}
endmodule

