// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module PageFlipper(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
  input         io_swapWrite,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:45:14
  output [31:0] io_addrRead,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:45:14
  output [31:0] io_addrWrite	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:45:14
);

  reg [1:0] rdIndexReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:59:27
  reg [1:0] wrIndexReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:60:27
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
      rdIndexReg <= 2'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:59:27
      wrIndexReg <= 2'h1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:60:27
    end
    else if (io_swapWrite) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:45:14
      rdIndexReg <= {1'h0, wrIndexReg[0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7, :59:27, :60:27, :74:{18,31}
      wrIndexReg <= {1'h0, ~(wrIndexReg[0])};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7, :60:27, :74:31, :75:{18,21}
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
        rdIndexReg = _RANDOM[/*Zero width*/ 1'b0][1:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7, :59:27
        wrIndexReg = _RANDOM[/*Zero width*/ 1'b0][3:2];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7, :59:27, :60:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_addrRead = {11'h121, rdIndexReg, 19'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7, :59:27, :80:{37,57}
  assign io_addrWrite = {11'h121, wrIndexReg, 19'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/PageFlipper.scala:44:7, :60:27, :80:{37,57}, :81:58
endmodule

