// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module PISO(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
  input        clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
  input        reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
  input        io_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input        io_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  output       io_isEmpty,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  output       io_isAlmostEmpty,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_0,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_1,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_2,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_3,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_4,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_5,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_6,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_7,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_8,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_9,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_10,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_11,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_12,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_13,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_14,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  input  [7:0] io_din_15,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
  output [7:0] io_dout	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
);

  reg  [7:0] pisoReg_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_4;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_5;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_7;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_8;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_9;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_10;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_11;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_12;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_13;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_14;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [7:0] pisoReg_15;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
  reg  [4:0] pisoCounterReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:62:31
  wire       _GEN = io_rd & (|pisoCounterReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:62:31, :65:34, :72:20
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
    if (io_wr) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
      pisoReg_0 <= io_din_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_1 <= io_din_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_2 <= io_din_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_3 <= io_din_3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_4 <= io_din_4;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_5 <= io_din_5;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_6 <= io_din_6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_7 <= io_din_7;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_8 <= io_din_8;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_9 <= io_din_9;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_10 <= io_din_10;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_11 <= io_din_11;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_12 <= io_din_12;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_13 <= io_din_13;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_14 <= io_din_14;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_15 <= io_din_15;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
    end
    else if (_GEN) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:72:20
      pisoReg_0 <= pisoReg_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_1 <= pisoReg_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_2 <= pisoReg_3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_3 <= pisoReg_4;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_4 <= pisoReg_5;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_5 <= pisoReg_6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_6 <= pisoReg_7;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_7 <= pisoReg_8;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_8 <= pisoReg_9;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_9 <= pisoReg_10;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_10 <= pisoReg_11;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_11 <= pisoReg_12;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_12 <= pisoReg_13;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_13 <= pisoReg_14;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_14 <= pisoReg_15;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
      pisoReg_15 <= pisoReg_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:61:20
    end
    if (reset)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
      pisoCounterReg <= 5'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:62:31, :65:34
    else if (io_wr)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:45:14
      pisoCounterReg <= 5'h10;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:62:31, :71:20
    else if (_GEN)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:72:20
      pisoCounterReg <= 5'(pisoCounterReg - 5'h1);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:62:31, :74:38
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
        end	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
        pisoReg_0 = _RANDOM[3'h0][7:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_1 = _RANDOM[3'h0][15:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_2 = _RANDOM[3'h0][23:16];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_3 = _RANDOM[3'h0][31:24];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_4 = _RANDOM[3'h1][7:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_5 = _RANDOM[3'h1][15:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_6 = _RANDOM[3'h1][23:16];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_7 = _RANDOM[3'h1][31:24];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_8 = _RANDOM[3'h2][7:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_9 = _RANDOM[3'h2][15:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_10 = _RANDOM[3'h2][23:16];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_11 = _RANDOM[3'h2][31:24];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_12 = _RANDOM[3'h3][7:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_13 = _RANDOM[3'h3][15:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_14 = _RANDOM[3'h3][23:16];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoReg_15 = _RANDOM[3'h3][31:24];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
        pisoCounterReg = _RANDOM[3'h4][4:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :62:31
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_isEmpty = ~(|pisoCounterReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :62:31, :65:34
  assign io_isAlmostEmpty = pisoCounterReg == 5'h1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :62:31, :66:40
  assign io_dout = pisoReg_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/PISO.scala:44:7, :61:20
endmodule

