// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module RegisterFile_2(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
  input         io_mem_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:48:14
  input  [1:0]  io_mem_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:48:14
  input  [1:0]  io_mem_mask,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:48:14
  input  [15:0] io_mem_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:48:14
  output [15:0] io_mem_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:48:14
  output [15:0] io_regs_0,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:48:14
  output [15:0] io_regs_1,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:48:14
  output [15:0] io_regs_2	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:48:14
);

  reg  [15:0] regs_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17
  reg  [15:0] regs_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17
  reg  [15:0] regs_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17
  reg  [15:0] casez_tmp;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:62:37
  always @(*) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:62:37
    casez (io_mem_addr)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:62:37
      2'b00:
        casez_tmp = regs_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17, :62:37
      2'b01:
        casez_tmp = regs_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17, :62:37
      2'b10:
        casez_tmp = regs_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17, :62:37
      default:
        casez_tmp = regs_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17, :62:37
    endcase	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:62:37
  end // always @(*)
  wire [7:0]  bytes_1 = io_mem_wr & io_mem_mask[1] ? io_mem_din[15:8] : casez_tmp[15:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:62:{23,37}, :66:{20,34,39,50,63}
  wire [7:0]  bytes_0 = io_mem_wr & io_mem_mask[0] ? io_mem_din[7:0] : casez_tmp[7:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:62:{23,37}, :66:{20,34,39,50,63}
  wire [15:0] _regs_T = {bytes_1, bytes_0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:62:23, :66:{39,50}, :70:17
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
    if (io_mem_addr == 2'h0)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :70:8
      regs_0 <= _regs_T;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17, :70:17
    if (io_mem_addr == 2'h1)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :70:8
      regs_1 <= _regs_T;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17, :70:17
    if (io_mem_addr == 2'h2)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :70:8
      regs_2 <= _regs_T;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:56:17, :70:17
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
        end	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
        regs_0 = _RANDOM[1'h0][15:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :56:17
        regs_1 = _RANDOM[1'h0][31:16];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :56:17
        regs_2 = _RANDOM[1'h1][15:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :56:17
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_mem_dout = casez_tmp;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :62:37
  assign io_regs_0 = regs_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :56:17
  assign io_regs_1 = regs_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :56:17
  assign io_regs_2 = regs_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/RegisterFile.scala:44:7, :56:17
endmodule

