// Generated by CIRCT firtool-1.135.0
module SinglePortRam(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:45:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:45:7
  input         io_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:49:14
  input         io_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:49:14
  input  [14:0] io_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:49:14
  input  [1:0]  io_mask,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:49:14
  input  [15:0] io_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:49:14
  output [15:0] io_dout	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:49:14
);

  single_port_ram #(
    .ADDR_WIDTH(15),
    .DATA_WIDTH(16),
    .DEPTH(0),
    .MASK_ENABLE("TRUE")
  ) ram (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:72:19
    .clk  (clock),
    .rd   (io_rd),
    .wr   (io_wr),
    .addr (io_addr),
    .mask (io_mask),
    .din  (io_din),
    .dout (io_dout)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/SinglePortRam.scala:72:19
endmodule

