// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Sound(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
  input         io_ctrl_oki_0_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [15:0] io_ctrl_oki_0_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  output [15:0] io_ctrl_oki_0_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input         io_ctrl_oki_1_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [15:0] io_ctrl_oki_1_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  output [15:0] io_ctrl_oki_1_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input         io_ctrl_nmk_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [22:0] io_ctrl_nmk_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [15:0] io_ctrl_nmk_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input         io_ctrl_ymz_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input         io_ctrl_ymz_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [22:0] io_ctrl_ymz_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [15:0] io_ctrl_ymz_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  output [15:0] io_ctrl_ymz_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input         io_ctrl_req,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [15:0] io_ctrl_data,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  output        io_ctrl_irq,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [3:0]  io_gameIndex,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [1:0]  io_gameConfig_sound_0_device,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  output        io_rom_0_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  output [24:0] io_rom_0_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [7:0]  io_rom_0_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input         io_rom_0_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input         io_rom_0_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  output [24:0] io_rom_1_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input  [7:0]  io_rom_1_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  input         io_rom_1_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
  output [15:0] io_audio	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
);

  wire        cs_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67
  wire        cs;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:72
  wire        _GEN;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:165:21
  wire        _arbiter_io_in_0_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  wire        _arbiter_io_in_1_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  wire [24:0] _arbiter_io_in_1_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  wire        _arbiter_io_in_2_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  wire [24:0] _arbiter_io_in_2_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  wire        _arbiter_io_in_3_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  wire [24:0] _arbiter_io_in_3_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  wire [7:0]  _arbiter_io_in_2_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  wire [7:0]  _arbiter_io_in_3_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  wire        _ym2203_io_cpu_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
  wire        _ym2203_io_cpu_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
  wire [7:0]  _ym2203_io_cpu_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
  wire        _ym2203_io_audio_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
  wire [15:0] _ym2203_io_audio_bits_psg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
  wire [15:0] _ym2203_io_audio_bits_fm;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
  wire        _ymz280b_io_cpu_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire [7:0]  _ymz280b_io_cpu_din;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire [7:0]  _ymz280b_io_rom_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire        _ymz280b_io_rom_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire        _ymz280b_io_rom_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire [7:0]  _ymz280b_io_cpu_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire        _ymz280b_io_rom_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire [23:0] _ymz280b_io_rom_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire        _ymz280b_io_audio_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire [15:0] _ymz280b_io_audio_bits_left;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  wire [7:0]  _oki_1_io_cpu_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire [17:0] _oki_1_io_rom_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire        _oki_1_io_audio_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire [13:0] _oki_1_io_audio_bits;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire [7:0]  _oki_0_io_cpu_din;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire [7:0]  _oki_0_io_rom_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire        _oki_0_io_rom_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire [7:0]  _oki_0_io_cpu_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire [17:0] _oki_0_io_rom_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire        _oki_0_io_audio_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire [13:0] _oki_0_io_audio_bits;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  wire [24:0] _nmk_io_addr_0_in;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19
  wire [24:0] _nmk_io_addr_1_in;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19
  wire [24:0] _nmk_io_addr_0_out;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19
  wire [24:0] _nmk_io_addr_1_out;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19
  wire        _soundRam_io_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:83:24
  wire        _soundRam_io_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:83:24
  wire [12:0] _soundRam_io_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:83:24
  wire [7:0]  _soundRam_io_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:83:24
  wire        _cpu_io_int;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire [15:0] _cpu_io_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire [7:0]  _cpu_io_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire        _cpu_io_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire        _cpu_io_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire        _cpu_io_rfsh;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire        _cpu_io_mreq;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire        _cpu_io_iorq;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  reg         reqReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:67:25
  reg  [15:0] dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:68:26
  reg  [3:0]  z80BankReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:69:27
  reg  [3:0]  okiBankHiReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:70:29
  reg  [3:0]  okiBankLoReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:71:29
  wire        _mem_addr_T_4 = io_gameIndex == 4'h2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:147:22
  wire [3:0]  mem_addr_bank = _oki_0_io_rom_addr[17] ? okiBankHiReg : okiBankLoReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:70:29, :71:29, :96:21, :146:{19,24}
  wire [24:0] mem_addr =
    _mem_addr_T_4 ? _nmk_io_addr_0_out : {4'h0, mem_addr_bank, _oki_0_io_rom_addr[16:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:69:27, :90:19, :96:21, :146:19, :147:{8,22}, :149:19
  wire [3:0]  mem_addr_bank_1 = _oki_1_io_rom_addr[17] ? okiBankHiReg : okiBankLoReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:70:29, :71:29, :96:21, :146:{19,24}
  assign _GEN = io_gameIndex == 4'h7;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:165:21
  assign cs = _cpu_io_addr < 16'h4000;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:72, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  assign cs_1 = (|(_cpu_io_addr[15:14])) & ~(_cpu_io_addr[15]);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:{58,67,72}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire [7:0]  _GEN_0 =
    cs_1 & _cpu_io_mreq & _cpu_io_rd ? _arbiter_io_in_3_dout : _arbiter_io_in_2_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:119:{15,27,38,48}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :119:23
  wire        cs_2 = _cpu_io_addr > 16'hDFFF;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:58, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire        _soundRam_io_wr_T = cs_2 & _cpu_io_mreq;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:58, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:97:20, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire [7:0]  _GEN_1 = _soundRam_io_wr_T & _cpu_io_rd ? _soundRam_io_dout : _GEN_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:97:20, :100:{27,38,48}, :119:{38,48}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :83:24
  wire [15:0] _GEN_2 = {8'h0, _cpu_io_addr[7:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:76:25, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire        _GEN_3 = _GEN_2 > 16'h2F & _GEN_2 < 16'h31 & _cpu_io_iorq & _cpu_io_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:{58,67,72}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:76:25, :163:{15,27}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire [7:0]  _GEN_4 = _GEN_3 ? dataReg[7:0] : _GEN_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:163:{15,27,38,48}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:100:{38,48}, :119:38, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:68:26, :137:42
  wire        _GEN_5 =
    (|(_cpu_io_addr[7:6])) & _GEN_2 < 16'h41 & _cpu_io_iorq & _cpu_io_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:{58,67,72}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:76:25, :163:{15,27}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire [7:0]  _GEN_6 = _GEN_5 ? dataReg[15:8] : _GEN_4;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:163:{15,27,38,48}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:100:38, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:68:26, :137:22
  wire        _ym2203_io_cpu_wr_T = _GEN_2 > 16'h4F & _GEN_2 < 16'h52 & _cpu_io_iorq;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:{58,67,72}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:76:25, :97:20, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire [7:0]  _GEN_7 = _ym2203_io_cpu_wr_T & _cpu_io_rd ? _ym2203_io_cpu_dout : _GEN_6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:97:20, :100:{27,38,48}, :163:{38,48}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :108:22
  wire        _oki_1_io_cpu_wr_T = _GEN_2 > 16'h5F & _GEN_2 < 16'h61 & _cpu_io_iorq;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:{58,67,72}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:76:25, :97:20, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  wire        oki_1_io_cpu_wr = _GEN ? _oki_1_io_cpu_wr_T & _cpu_io_wr : io_ctrl_oki_1_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:97:{14,20,32}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :97:16, :165:{21,42}
  wire [7:0]  oki_1_io_cpu_din = _GEN ? _cpu_io_dout : io_ctrl_oki_1_din[7:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:99:15, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :97:16, :165:{21,42}
  wire [7:0]  cpu_io_din = _oki_1_io_cpu_wr_T & _cpu_io_rd ? _oki_1_io_cpu_dout : _GEN_7;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:97:20, :100:{27,38,48}, :163:38, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :96:21
  reg  [15:0] io_audio_r;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:180:14
  reg  [15:0] io_audio_r_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:181:14
  reg  [15:0] io_audio_r_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:182:14
  reg  [13:0] io_audio_r_3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:183:14
  reg  [13:0] io_audio_r_4;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:184:14
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
      reqReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:67:25
      z80BankReg <= 4'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:69:27
      okiBankHiReg <= 4'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:69:27, :70:29
      okiBankLoReg <= 4'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:69:27, :71:29
    end
    else begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
      reqReg <= ~(_GEN & (_GEN_5 | _GEN_3)) & (io_ctrl_req | reqReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:163:{15,27,38}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:67:25, :136:12, :165:{21,42}
      if (_GEN & _cpu_io_addr[7:0] == 8'h0 & _cpu_io_iorq & _cpu_io_wr)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:72, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:76:25, :172:{15,27,38}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:69:27, :74:19, :165:{21,42}, :170:48
        z80BankReg <= _cpu_io_dout[3:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:69:27, :74:19, :170:55
      if (_GEN & _GEN_2 > 16'h6F & _GEN_2 < 16'h71 & _cpu_io_iorq & _cpu_io_wr) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:{58,67,72}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:76:25, :172:{15,27,38}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:70:29, :74:19, :160:18, :165:{21,42}
        okiBankHiReg <= {2'h0, _cpu_io_dout[5:4]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :70:29, :74:19, :160:{25,32}
        okiBankLoReg <= {2'h0, _cpu_io_dout[1:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :71:29, :74:19, :161:{25,32}
      end
    end
    if (io_ctrl_req)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:50:14
      dataReg <= io_ctrl_data;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:68:26
    if (_ymz280b_io_audio_valid)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
      io_audio_r <= _ymz280b_io_audio_bits_left;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23, :180:14
    if (_ym2203_io_audio_valid) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
      io_audio_r_1 <= _ym2203_io_audio_bits_psg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22, :181:14
      io_audio_r_2 <= _ym2203_io_audio_bits_fm;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22, :182:14
    end
    if (_oki_0_io_audio_valid)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
      io_audio_r_3 <= _oki_0_io_audio_bits;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21, :183:14
    if (_oki_1_io_audio_valid)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
      io_audio_r_4 <= _oki_1_io_audio_bits;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21, :184:14
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
        end	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
        reqReg = _RANDOM[2'h0][0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :67:25
        dataReg = _RANDOM[2'h0][16:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :67:25, :68:26
        z80BankReg = _RANDOM[2'h0][20:17];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :67:25, :69:27
        okiBankHiReg = _RANDOM[2'h0][24:21];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :67:25, :70:29
        okiBankLoReg = _RANDOM[2'h0][28:25];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :67:25, :71:29
        io_audio_r = {_RANDOM[2'h0][31:29], _RANDOM[2'h1][12:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :67:25, :180:14
        io_audio_r_1 = _RANDOM[2'h1][28:13];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :180:14, :181:14
        io_audio_r_2 = {_RANDOM[2'h1][31:29], _RANDOM[2'h2][12:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :180:14, :182:14
        io_audio_r_3 = _RANDOM[2'h2][26:13];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :182:14, :183:14
        io_audio_r_4 = {_RANDOM[2'h2][31:27], _RANDOM[2'h3][8:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :182:14, :184:14
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  CPU_1 cpu (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
    .clock   (clock),
    .reset   (reset),
    .io_addr (_cpu_io_addr),
    .io_din  (cpu_io_din),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:100:{38,48}
    .io_dout (_cpu_io_dout),
    .io_rd   (_cpu_io_rd),
    .io_wr   (_cpu_io_wr),
    .io_rfsh (_cpu_io_rfsh),
    .io_mreq (_cpu_io_mreq),
    .io_iorq (_cpu_io_iorq),
    .io_int  (_cpu_io_int),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
    .io_nmi  (reqReg)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:67:25
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
  assign _soundRam_io_rd = _GEN & cs_2 & ~_cpu_io_rfsh;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:58, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:96:{14,20}, :117:23, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/MemIO.scala:317:8, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :83:24, :165:{21,42}
  assign _soundRam_io_wr = _GEN & _soundRam_io_wr_T & _cpu_io_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:97:{14,20,32}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/MemIO.scala:318:8, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :83:24, :165:{21,42}
  assign _soundRam_io_addr = _cpu_io_addr[12:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:98:16, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :83:24
  SinglePortRam_1 soundRam (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:83:24
    .clock   (clock),
    .io_rd   (_soundRam_io_rd),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:83:24
    .io_wr   (_soundRam_io_wr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:83:24
    .io_addr (_soundRam_io_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:83:24
    .io_din  (_cpu_io_dout),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
    .io_dout (_soundRam_io_dout)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:83:24
  assign _nmk_io_addr_0_in = {7'h0, _oki_0_io_rom_addr};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/NMK112.scala:80:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19, :96:21
  assign _nmk_io_addr_1_in = {7'h0, _oki_1_io_rom_addr};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/NMK112.scala:80:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19, :96:21
  NMK112 nmk (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19
    .clock         (clock),
    .io_cpu_wr     (io_ctrl_nmk_wr),
    .io_cpu_addr   (io_ctrl_nmk_addr),
    .io_cpu_din    (io_ctrl_nmk_din),
    .io_addr_0_in  (_nmk_io_addr_0_in),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19
    .io_addr_0_out (_nmk_io_addr_0_out),
    .io_addr_1_in  (_nmk_io_addr_1_in),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19
    .io_addr_1_out (_nmk_io_addr_1_out)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:90:19
  assign _oki_0_io_cpu_din = io_ctrl_oki_0_din[7:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21, :97:16
  OKIM6295 oki_0 (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
    .clock          (clock),
    .reset          (reset),
    .io_cpu_wr      (io_ctrl_oki_0_wr),
    .io_cpu_din     (_oki_0_io_cpu_din),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
    .io_cpu_dout    (_oki_0_io_cpu_dout),
    .io_rom_addr    (_oki_0_io_rom_addr),
    .io_rom_dout    (_oki_0_io_rom_dout),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
    .io_rom_valid   (_oki_0_io_rom_valid),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
    .io_audio_valid (_oki_0_io_audio_valid),
    .io_audio_bits  (_oki_0_io_audio_bits)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  OKIM6295_1 oki_1 (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
    .clock          (clock),
    .reset          (reset),
    .io_cpu_wr      (oki_1_io_cpu_wr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:97:14, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:97:16, :165:42
    .io_cpu_din     (oki_1_io_cpu_din),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:99:15, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:97:16, :165:42
    .io_cpu_dout    (_oki_1_io_cpu_dout),
    .io_rom_addr    (_oki_1_io_rom_addr),
    .io_rom_dout    (io_rom_1_dout),
    .io_rom_valid   (io_rom_1_valid),
    .io_audio_valid (_oki_1_io_audio_valid),
    .io_audio_bits  (_oki_1_io_audio_bits)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:96:21
  assign _ymz280b_io_cpu_addr = io_ctrl_ymz_addr[0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23, :103:18
  assign _ymz280b_io_cpu_din = io_ctrl_ymz_din[7:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23, :103:18
  YMZ280B ymz280b (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
    .clock              (clock),
    .reset              (reset),
    .io_cpu_rd          (io_ctrl_ymz_rd),
    .io_cpu_wr          (io_ctrl_ymz_wr),
    .io_cpu_addr        (_ymz280b_io_cpu_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
    .io_cpu_din         (_ymz280b_io_cpu_din),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
    .io_cpu_dout        (_ymz280b_io_cpu_dout),
    .io_rom_rd          (_ymz280b_io_rom_rd),
    .io_rom_addr        (_ymz280b_io_rom_addr),
    .io_rom_dout        (_ymz280b_io_rom_dout),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
    .io_rom_wait_n      (_ymz280b_io_rom_wait_n),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
    .io_rom_valid       (_ymz280b_io_rom_valid),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
    .io_audio_valid     (_ymz280b_io_audio_valid),
    .io_audio_bits_left (_ymz280b_io_audio_bits_left),
    .io_irq             (io_ctrl_irq)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23
  assign _ym2203_io_cpu_wr = _GEN & _ym2203_io_cpu_wr_T & _cpu_io_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:97:{14,20,32}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/MemIO.scala:318:8, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :108:22, :165:{21,42}
  assign _ym2203_io_cpu_addr = _cpu_io_addr[0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/IOMap.scala:98:16, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :108:22
  YM2203 ym2203 (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
    .clock             (clock),
    .reset             (reset),
    .io_cpu_wr         (_ym2203_io_cpu_wr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
    .io_cpu_addr       (_ym2203_io_cpu_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
    .io_cpu_din        (_cpu_io_dout),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19
    .io_cpu_dout       (_ym2203_io_cpu_dout),
    .io_irq            (_cpu_io_int),
    .io_audio_valid    (_ym2203_io_audio_valid),
    .io_audio_bits_psg (_ym2203_io_audio_bits_psg),
    .io_audio_bits_fm  (_ym2203_io_audio_bits_fm)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:108:22
  assign _arbiter_io_in_0_rd = io_gameConfig_sound_0_device == 2'h2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :119:23, :121:79
  assign _arbiter_io_in_1_rd = io_gameConfig_sound_0_device == 2'h1 & _ymz280b_io_rom_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:135:21, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :102:23, :119:23, :122:57
  assign _arbiter_io_in_1_addr = {1'h0, _ymz280b_io_rom_addr};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/arbiter/AsyncReadMemArbiter.scala:68:54, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:102:23, :119:23
  assign _arbiter_io_in_2_rd =
    (&io_gameConfig_sound_0_device) & _GEN & cs & ~_cpu_io_rfsh;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:72, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:117:{14,20,23}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:135:21, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/MemIO.scala:83:8, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :119:23, :123:50, :165:{21,42}
  assign _arbiter_io_in_2_addr = {9'h0, _cpu_io_addr};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:118:16, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :119:23
  assign _arbiter_io_in_3_rd =
    (&io_gameConfig_sound_0_device) & _GEN & cs_1 & ~_cpu_io_rfsh;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:67, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:117:{14,20,23}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/AsyncMemIO.scala:135:21, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/mem/MemIO.scala:83:8, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:74:19, :119:23, :123:50, :165:{21,42}
  assign _arbiter_io_in_3_addr = {7'h0, z80BankReg, _cpu_io_addr[13:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/cpu/z80/MemMap.scala:118:16, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/NMK112.scala:80:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:69:27, :74:19, :119:23, :167:76
  AsyncReadMemArbiter arbiter (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
    .clock          (clock),
    .reset          (reset),
    .io_in_0_rd     (_arbiter_io_in_0_rd),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
    .io_in_0_addr   (mem_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:147:8
    .io_in_0_dout   (_oki_0_io_rom_dout),
    .io_in_0_valid  (_oki_0_io_rom_valid),
    .io_in_1_rd     (_arbiter_io_in_1_rd),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
    .io_in_1_addr   (_arbiter_io_in_1_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
    .io_in_1_dout   (_ymz280b_io_rom_dout),
    .io_in_1_wait_n (_ymz280b_io_rom_wait_n),
    .io_in_1_valid  (_ymz280b_io_rom_valid),
    .io_in_2_rd     (_arbiter_io_in_2_rd),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
    .io_in_2_addr   (_arbiter_io_in_2_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
    .io_in_2_dout   (_arbiter_io_in_2_dout),
    .io_in_3_rd     (_arbiter_io_in_3_rd),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
    .io_in_3_addr   (_arbiter_io_in_3_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
    .io_in_3_dout   (_arbiter_io_in_3_dout),
    .io_out_rd      (io_rom_0_rd),
    .io_out_addr    (io_rom_0_addr),
    .io_out_dout    (io_rom_0_dout),
    .io_out_wait_n  (io_rom_0_wait_n),
    .io_out_valid   (io_rom_0_valid)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:119:23
  AudioMixer io_audio_mixer (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/AudioMixer.scala:100:23
    .clock   (clock),
    .io_in_4 (io_audio_r_4),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:184:14
    .io_in_3 (io_audio_r_3),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:183:14
    .io_in_2 (io_audio_r_2),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:182:14
    .io_in_1 (io_audio_r_1),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:181:14
    .io_in_0 (io_audio_r),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:180:14
    .io_out  (io_audio)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/snd/AudioMixer.scala:100:23
  assign io_ctrl_oki_0_dout = {8'h0, _oki_0_io_cpu_dout};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :96:21, :97:16
  assign io_ctrl_oki_1_dout = {8'h0, _oki_1_io_cpu_dout};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :96:21, :97:16
  assign io_ctrl_ymz_dout = {8'h0, _ymz280b_io_cpu_dout};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :102:23, :103:18
  assign io_rom_1_addr =
    _mem_addr_T_4
      ? _nmk_io_addr_1_out
      : {4'h0, mem_addr_bank_1, _oki_1_io_rom_addr[16:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/snd/Sound.scala:49:7, :69:27, :90:19, :96:21, :146:19, :147:{8,22}, :149:19
endmodule

