// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SpriteFrameBuffer(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
  input         io_videoClock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input         io_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input         io_swap,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input  [8:0]  io_video_pos_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input         io_video_hBlank,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input  [8:0]  io_lineBuffer_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  output [15:0] io_lineBuffer_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input         io_frameBuffer_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input  [16:0] io_frameBuffer_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input  [15:0] io_frameBuffer_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  output        io_frameBuffer_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  output        io_ddr_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  output        io_ddr_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  output [31:0] io_ddr_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  output [7:0]  io_ddr_mask,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  output [63:0] io_ddr_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input  [63:0] io_ddr_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input         io_ddr_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input         io_ddr_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  output [7:0]  io_ddr_burstLength,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
  input         io_ddr_burstDone	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:62:14
);

  wire [31:0] _ddrArbiter_io_in_0_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:130:26
  wire [31:0] _ddrArbiter_io_in_1_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:130:26
  wire [31:0] _ddrArbiter_io_in_2_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:130:26
  wire        _frameBufferDma_io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
  wire        _frameBufferDma_io_out_burstDone;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
  wire        _frameBufferDma_io_out_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
  wire [31:0] _frameBufferDma_io_out_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
  wire [63:0] _frameBufferDma_io_out_din;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
  wire        _queue_io_out_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
  wire        _queue_io_out_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
  wire [31:0] _queue_io_out_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
  wire [7:0]  _queue_io_out_mask;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
  wire [63:0] _queue_io_out_din;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
  wire        _lineBufferDma_io_start;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
  wire [63:0] _lineBufferDma_io_in_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
  wire        _lineBufferDma_io_in_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
  wire        _lineBufferDma_io_in_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
  wire        _lineBufferDma_io_in_burstDone;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
  wire        _lineBufferDma_io_in_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
  wire [31:0] _lineBufferDma_io_in_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
  wire [31:0] _lineBufferDma_io_out_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
  wire [31:0] _pageFlipper_io_addrRead;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:96:27
  wire [31:0] _pageFlipper_io_addrWrite;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:96:27
  wire        _lineBuffer_io_portA_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:83:26
  wire [6:0]  _lineBuffer_io_portA_addr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:83:26
  wire [63:0] _lineBuffer_io_portA_din;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:83:26
  reg         hBlank_r;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:79:29
  reg         hBlank;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:79:29
  reg         hBlankRising_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:44
  wire        frameBufferDma_io_start = io_enable & io_swap;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:99:41
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
    hBlank_r <= io_video_hBlank;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:79:29
    hBlank <= hBlank_r;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:79:29
    hBlankRising_REG <= hBlank;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:44, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:79:29
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
        hBlank_r = _RANDOM[/*Zero width*/ 1'b0][0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7, :79:29
        hBlank = _RANDOM[/*Zero width*/ 1'b0][1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7, :79:29
        hBlankRising_REG = _RANDOM[/*Zero width*/ 1'b0][2];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:44, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7, :79:29
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:61:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign _lineBuffer_io_portA_addr = _lineBufferDma_io_out_addr[9:3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:83:26, :102:29, :105:24, :106:14
  TrueDualPortRam_11 lineBuffer (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:83:26
    .clock         (clock),
    .io_clockB     (io_videoClock),
    .io_portA_wr   (_lineBuffer_io_portA_wr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:83:26
    .io_portA_addr (_lineBuffer_io_portA_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:83:26
    .io_portA_din  (_lineBuffer_io_portA_din),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:83:26
    .io_portB_addr (io_lineBuffer_addr),
    .io_portB_dout (io_lineBuffer_dout)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:83:26
  PageFlipper pageFlipper (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:96:27
    .clock        (clock),
    .reset        (reset),
    .io_swapWrite (frameBufferDma_io_start),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:99:41
    .io_addrRead  (_pageFlipper_io_addrRead),
    .io_addrWrite (_pageFlipper_io_addrWrite)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:96:27
  assign _lineBufferDma_io_start = io_enable & hBlank & ~hBlankRising_REG;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:158:{33,36,44}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:79:29, :102:29, :103:39
  BurstReadDMA_1 lineBufferDma (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
    .clock           (clock),
    .reset           (reset),
    .io_start        (_lineBufferDma_io_start),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
    .io_in_rd        (_lineBufferDma_io_in_rd),
    .io_in_addr      (_lineBufferDma_io_in_addr),
    .io_in_dout      (_lineBufferDma_io_in_dout),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
    .io_in_wait_n    (_lineBufferDma_io_in_wait_n),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
    .io_in_valid     (_lineBufferDma_io_in_valid),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
    .io_in_burstDone (_lineBufferDma_io_in_burstDone),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
    .io_out_wr       (_lineBuffer_io_portA_wr),
    .io_out_addr     (_lineBufferDma_io_out_addr),
    .io_out_din      (_lineBuffer_io_portA_din)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
  RequestQueue queue (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
    .clock         (clock),
    .io_enable     (io_enable),
    .io_readClock  (clock),
    .io_in_wr      (io_frameBuffer_wr),
    .io_in_addr    (io_frameBuffer_addr),
    .io_in_din     (io_frameBuffer_din),
    .io_in_wait_n  (io_frameBuffer_wait_n),
    .io_out_wr     (_queue_io_out_wr),
    .io_out_addr   (_queue_io_out_addr),
    .io_out_mask   (_queue_io_out_mask),
    .io_out_din    (_queue_io_out_din),
    .io_out_wait_n (_queue_io_out_wait_n)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
  BurstWriteDMA frameBufferDma (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
    .clock            (clock),
    .reset            (reset),
    .io_start         (frameBufferDma_io_start),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:99:41
    .io_out_wr        (_frameBufferDma_io_out_wr),
    .io_out_addr      (_frameBufferDma_io_out_addr),
    .io_out_din       (_frameBufferDma_io_out_din),
    .io_out_wait_n    (_frameBufferDma_io_out_wait_n),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
    .io_out_burstDone (_frameBufferDma_io_out_burstDone)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
  assign _ddrArbiter_io_in_0_addr =
    32'(_lineBufferDma_io_in_addr
        + 32'(_pageFlipper_io_addrRead + {13'h0, 9'(io_video_pos_y + 9'h1), 10'h0}));	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:96:27, :102:29, :127:{47,54}, :130:26, :132:{35,61}
  assign _ddrArbiter_io_in_1_addr =
    32'(_frameBufferDma_io_out_addr + _pageFlipper_io_addrWrite);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:96:27, :120:30, :130:26, :133:37
  assign _ddrArbiter_io_in_2_addr = 32'(_queue_io_out_addr + _pageFlipper_io_addrWrite);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:96:27, :109:21, :130:26, :134:28
  BurstMemArbiter_2 ddrArbiter (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:130:26
    .clock              (clock),
    .reset              (reset),
    .io_in_0_rd         (_lineBufferDma_io_in_rd),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:102:29
    .io_in_0_addr       (_ddrArbiter_io_in_0_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:130:26
    .io_in_0_dout       (_lineBufferDma_io_in_dout),
    .io_in_0_wait_n     (_lineBufferDma_io_in_wait_n),
    .io_in_0_valid      (_lineBufferDma_io_in_valid),
    .io_in_0_burstDone  (_lineBufferDma_io_in_burstDone),
    .io_in_1_wr         (_frameBufferDma_io_out_wr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
    .io_in_1_addr       (_ddrArbiter_io_in_1_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:130:26
    .io_in_1_din        (_frameBufferDma_io_out_din),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:120:30
    .io_in_1_wait_n     (_frameBufferDma_io_out_wait_n),
    .io_in_1_burstDone  (_frameBufferDma_io_out_burstDone),
    .io_in_2_wr         (_queue_io_out_wr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
    .io_in_2_addr       (_ddrArbiter_io_in_2_addr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:130:26
    .io_in_2_mask       (_queue_io_out_mask),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
    .io_in_2_din        (_queue_io_out_din),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:109:21
    .io_in_2_wait_n     (_queue_io_out_wait_n),
    .io_out_rd          (io_ddr_rd),
    .io_out_wr          (io_ddr_wr),
    .io_out_addr        (io_ddr_addr),
    .io_out_mask        (io_ddr_mask),
    .io_out_din         (io_ddr_din),
    .io_out_dout        (io_ddr_dout),
    .io_out_wait_n      (io_ddr_wait_n),
    .io_out_valid       (io_ddr_valid),
    .io_out_burstLength (io_ddr_burstLength),
    .io_out_burstDone   (io_ddr_burstDone)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/fb/SpriteFrameBuffer.scala:130:26
endmodule

