// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SpriteDecoder(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
  input  [1:0]  io_format,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output        io_tileRom_ready,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  input         io_tileRom_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  input  [63:0] io_tileRom_bits,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  input         io_pixelData_ready,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output        io_pixelData_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_0,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_1,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_2,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_3,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_4,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_5,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_6,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_7,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_8,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_9,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_10,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_11,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_12,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_13,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_14,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
  output [7:0]  io_pixelData_bits_15	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:50:14
);

  reg          pendingReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:63:27
  reg          validReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:64:25
  reg          toggleReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:65:26
  reg  [127:0] dataReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20
  wire         _bits_T_114 = io_format == 2'h2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:73:111
  wire [3:0]   _GEN = _bits_T_114 ? dataReg[15:12] : dataReg[3:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_0 = _bits_T_114 ? dataReg[11:8] : dataReg[7:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_1 = _bits_T_114 ? dataReg[7:4] : dataReg[11:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_2 = _bits_T_114 ? dataReg[3:0] : dataReg[15:12];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_3 = _bits_T_114 ? dataReg[31:28] : dataReg[19:16];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_4 = _bits_T_114 ? dataReg[27:24] : dataReg[23:20];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_5 = _bits_T_114 ? dataReg[23:20] : dataReg[27:24];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_6 = _bits_T_114 ? dataReg[19:16] : dataReg[31:28];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_7 = _bits_T_114 ? dataReg[47:44] : dataReg[35:32];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_8 = _bits_T_114 ? dataReg[43:40] : dataReg[39:36];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_9 = _bits_T_114 ? dataReg[39:36] : dataReg[43:40];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_10 = _bits_T_114 ? dataReg[35:32] : dataReg[47:44];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_11 = _bits_T_114 ? dataReg[63:60] : dataReg[51:48];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_12 = _bits_T_114 ? dataReg[59:56] : dataReg[55:52];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_13 = _bits_T_114 ? dataReg[55:52] : dataReg[59:56];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire [3:0]   _GEN_14 = _bits_T_114 ? dataReg[51:48] : dataReg[63:60];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:{80,111}
  wire         start = io_pixelData_ready & ~pendingReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:63:27, :69:{34,37}
  wire         _GEN_15 = pendingReg & io_tileRom_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:63:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  wire         _GEN_16 = _GEN_15 & (~(&io_format) | toggleReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:60:26, :65:26, :70:{14,22}, :79:15, :86:25, :87:16, :88:18, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
      pendingReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:63:27
      validReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:63:27, :64:25
      toggleReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:63:27, :65:26
    end
    else begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
      pendingReg <= ~_GEN_16 & (start | pendingReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:63:27, :69:34, :79:15, :80:16, :86:25, :87:16, :88:18
      validReg <= _GEN_16 | ~start & validReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:64:25, :69:34, :79:15, :81:14, :86:25, :87:16, :88:18, :89:16
      toggleReg <= _GEN_15 ? ~toggleReg : ~start & toggleReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:64:25, :65:26, :69:34, :79:15, :81:14, :82:15, :86:25, :92:{15,18}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
    end
    if (_GEN_15)	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      dataReg <= {dataReg[63:0], io_tileRom_bits};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:66:20, :73:80, :91:57
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
        end	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
        pendingReg = _RANDOM[3'h0][0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :63:27
        validReg = _RANDOM[3'h0][1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :63:27, :64:25
        toggleReg = _RANDOM[3'h0][2];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :63:27, :65:26
        dataReg =
          {_RANDOM[3'h0][31:3],
           _RANDOM[3'h1],
           _RANDOM[3'h2],
           _RANDOM[3'h3],
           _RANDOM[3'h4][2:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :63:27, :66:20
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_tileRom_ready = pendingReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :63:27
  assign io_pixelData_valid = validReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :64:25
  assign io_pixelData_bits_0 =
    (&io_format) ? {dataReg[67:64], dataReg[75:72]} : {4'h0, _GEN};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_1 =
    (&io_format) ? {dataReg[71:68], dataReg[79:76]} : {4'h0, _GEN_0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_2 =
    (&io_format) ? {dataReg[83:80], dataReg[91:88]} : {4'h0, _GEN_1};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_3 =
    (&io_format) ? {dataReg[87:84], dataReg[95:92]} : {4'h0, _GEN_2};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_4 =
    (&io_format) ? {dataReg[99:96], dataReg[107:104]} : {4'h0, _GEN_3};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_5 =
    (&io_format) ? {dataReg[103:100], dataReg[111:108]} : {4'h0, _GEN_4};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_6 =
    (&io_format) ? {dataReg[115:112], dataReg[123:120]} : {4'h0, _GEN_5};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_7 =
    (&io_format) ? {dataReg[119:116], dataReg[127:124]} : {4'h0, _GEN_6};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_8 =
    (&io_format) ? {dataReg[3:0], dataReg[11:8]} : {4'h0, _GEN_7};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_9 =
    (&io_format) ? {dataReg[7:4], dataReg[15:12]} : {4'h0, _GEN_8};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_10 =
    (&io_format) ? {dataReg[19:16], dataReg[27:24]} : {4'h0, _GEN_9};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_11 =
    (&io_format) ? {dataReg[23:20], dataReg[31:28]} : {4'h0, _GEN_10};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_12 =
    (&io_format) ? {dataReg[35:32], dataReg[43:40]} : {4'h0, _GEN_11};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_13 =
    (&io_format) ? {dataReg[39:36], dataReg[47:44]} : {4'h0, _GEN_12};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_14 =
    (&io_format) ? {dataReg[51:48], dataReg[59:56]} : {4'h0, _GEN_13};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
  assign io_pixelData_bits_15 =
    (&io_format) ? {dataReg[55:52], dataReg[63:60]} : {4'h0, _GEN_14};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteDecoder.scala:49:7, :60:26, :66:20, :73:111, :113:17, :129:26
endmodule

