// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SpriteBlitter(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
  input         clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
  input         reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
  input         io_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  output        io_busy,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  output        io_config_ready,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input         io_config_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [1:0]  io_config_bits_sprite_priority,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [5:0]  io_config_bits_sprite_colorCode,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input         io_config_bits_sprite_hFlip,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input         io_config_bits_sprite_vFlip,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [17:0] io_config_bits_sprite_pos_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [17:0] io_config_bits_sprite_pos_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_config_bits_sprite_cols,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_config_bits_sprite_rows,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [15:0] io_config_bits_sprite_zoom_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [15:0] io_config_bits_sprite_zoom_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input         io_config_bits_hFlip,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [8:0]  io_video_regs_size_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [8:0]  io_video_regs_size_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  output        io_pixelData_ready,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input         io_pixelData_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_0,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_1,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_2,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_3,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_4,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_5,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_6,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_7,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_8,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_9,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_10,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_11,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_12,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_13,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_14,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input  [7:0]  io_pixelData_bits_15,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  output        io_frameBuffer_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  output [16:0] io_frameBuffer_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  output [15:0] io_frameBuffer_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
  input         io_frameBuffer_wait_n	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
);

  wire        pixelDataReady;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:107:46
  wire        _piso_io_rd;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20
  wire        _piso_io_wr;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20
  wire        _piso_io_isEmpty;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20
  wire        _piso_io_isAlmostEmpty;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20
  wire [7:0]  _piso_io_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20
  reg         busyReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:70:24
  reg  [1:0]  configReg_sprite_priority;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg  [5:0]  configReg_sprite_colorCode;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg         configReg_sprite_hFlip;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg         configReg_sprite_vFlip;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg  [17:0] configReg_sprite_pos_x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg  [17:0] configReg_sprite_pos_y;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg  [7:0]  configReg_sprite_cols;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg  [7:0]  configReg_sprite_rows;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg  [15:0] configReg_sprite_zoom_x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg  [15:0] configReg_sprite_zoom_y;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg         configReg_hFlip;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  wire        _GEN = busyReg & ~_piso_io_isEmpty & io_frameBuffer_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:70:24, :74:20, :84:{78,81,92}
  reg  [11:0] x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22
  wire        wrap_wrap =
    x == 12'({configReg_sprite_cols, 4'h0} - 12'h1) | configReg_sprite_cols == 8'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Vec2.scala:82:34, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, :69:{22,29,35,41}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  wire        xWrap = _GEN & wrap_wrap;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:69:35, :92:24, :93:{48,55}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:84:{78,92}
  reg  [11:0] y;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22
  wire        wrap_wrap_1 =
    y == 12'({configReg_sprite_rows, 4'h0} - 12'h1) | configReg_sprite_rows == 8'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Vec2.scala:82:34, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, :69:{22,29,35,41}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
  reg  [19:0] posReg_x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:88:25
  reg  [19:0] posReg_y;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:88:25
  reg  [1:0]  penReg_priority;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:92:25
  reg  [5:0]  penReg_palette;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:92:25
  reg  [7:0]  penReg_color;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:92:25
  reg         validReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:93:27
  wire        blitDone = xWrap & wrap_wrap_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:69:35, :92:24, :93:{48,55}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:99:24
  wire        configReady = ~busyReg | blitDone;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:92:24, :93:{48,55}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:70:24, :99:24, :103:{21,30}
  assign pixelDataReady =
    io_frameBuffer_wait_n & (_piso_io_isEmpty | _piso_io_isAlmostEmpty);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20, :107:{46,60}
  wire [27:0] posReg_x_0 = 28'({16'h0, x} * {12'h0, configReg_sprite_zoom_x});	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28, :140:19
  wire [27:0] posReg_y_0 = 28'({16'h0, y} * {12'h0, configReg_sprite_zoom_y});	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28, :140:19, :141:19
  wire [27:0] posReg_x_ =
    configReg_sprite_hFlip
      ? 28'(28'({8'h0, configReg_sprite_cols, 12'h0} - posReg_x_0) - 28'h100)
      : posReg_x_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28, :140:19, :144:{17,39,43}
  wire [27:0] _posReg_adjusted_T =
    28'({{10{configReg_sprite_pos_x[17]}}, configReg_sprite_pos_x} + posReg_x_);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Vec2.scala:125:42, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28, :144:17
  wire [27:0] posReg_y_ =
    configReg_sprite_vFlip
      ? 28'(28'({8'h0, configReg_sprite_rows, 12'h0} - posReg_y_0) - 28'h100)
      : posReg_y_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28, :141:19, :145:{17,39,43}
  wire [27:0] _posReg_adjusted_T_3 =
    28'({{10{configReg_sprite_pos_y[17]}}, configReg_sprite_pos_y} + posReg_y_);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Vec2.scala:125:59, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28, :145:17
  wire        _configReg_T = configReady & io_config_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:103:30, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
      busyReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:70:24
      x <= 12'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22
      y <= 12'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22
    end
    else begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
      busyReg <= _configReg_T | ~blitDone & busyReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:92:24, :93:{48,55}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:70:24, :99:24, :110:{24,34,65,75}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      if (_GEN)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:84:{78,92}
        x <= wrap_wrap ? 12'h0 : 12'(x + 12'h1);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, :69:35, :70:{11,20}, :71:{16,24}
      if (xWrap)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:92:24, :93:{48,55}
        y <= wrap_wrap_1 ? 12'h0 : 12'(y + 12'h1);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, :69:35, :70:{11,20}, :71:{16,24}
    end
    if (_configReg_T) begin	// src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
      configReg_sprite_priority <= io_config_bits_sprite_priority;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_sprite_colorCode <= io_config_bits_sprite_colorCode;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_sprite_hFlip <= io_config_bits_sprite_hFlip;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_sprite_vFlip <= io_config_bits_sprite_vFlip;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_sprite_pos_x <= io_config_bits_sprite_pos_x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_sprite_pos_y <= io_config_bits_sprite_pos_y;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_sprite_cols <= io_config_bits_sprite_cols;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_sprite_rows <= io_config_bits_sprite_rows;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_sprite_zoom_x <= io_config_bits_sprite_zoom_x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_sprite_zoom_y <= io_config_bits_sprite_zoom_y;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
      configReg_hFlip <= io_config_bits_hFlip;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28
    end
    if (io_frameBuffer_wait_n) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:54:14
      posReg_x <= _posReg_adjusted_T[27:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Vec2.scala:125:42, :137:34, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:88:25
      posReg_y <= _posReg_adjusted_T_3[27:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Vec2.scala:125:59, :137:56, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:88:25
      penReg_priority <= configReg_sprite_priority;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28, :92:25
      penReg_palette <= configReg_sprite_colorCode;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:71:28, :92:25
      penReg_color <= _piso_io_dout;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20, :92:25
      validReg <= ~_piso_io_isEmpty;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20, :84:81, :93:27
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
        end	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
        busyReg = _RANDOM[3'h0][0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :70:24
        configReg_sprite_priority = _RANDOM[3'h0][2:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :70:24, :71:28
        configReg_sprite_colorCode = _RANDOM[3'h0][8:3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :70:24, :71:28
        configReg_sprite_hFlip = _RANDOM[3'h0][27];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :70:24, :71:28
        configReg_sprite_vFlip = _RANDOM[3'h0][28];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :70:24, :71:28
        configReg_sprite_pos_x = {_RANDOM[3'h0][31:29], _RANDOM[3'h1][14:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :70:24, :71:28
        configReg_sprite_pos_y = {_RANDOM[3'h1][31:15], _RANDOM[3'h2][0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :71:28
        configReg_sprite_cols = _RANDOM[3'h2][8:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :71:28
        configReg_sprite_rows = _RANDOM[3'h2][16:9];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :71:28
        configReg_sprite_zoom_x = {_RANDOM[3'h2][31:17], _RANDOM[3'h3][0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :71:28
        configReg_sprite_zoom_y = _RANDOM[3'h3][16:1];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :71:28
        configReg_hFlip = _RANDOM[3'h3][17];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :71:28
        x = _RANDOM[3'h3][30:19];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :71:28
        y = {_RANDOM[3'h3][31], _RANDOM[3'h4][10:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :71:28
        posReg_x = _RANDOM[3'h4][30:11];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :88:25
        posReg_y = {_RANDOM[3'h4][31], _RANDOM[3'h5][18:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :88:25
        penReg_priority = _RANDOM[3'h5][20:19];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :88:25, :92:25
        penReg_palette = _RANDOM[3'h5][26:21];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :88:25, :92:25
        penReg_color = {_RANDOM[3'h5][31:27], _RANDOM[3'h6][2:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :88:25, :92:25
        validReg = _RANDOM[3'h6][3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :92:25, :93:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign _piso_io_rd = busyReg & io_frameBuffer_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:70:24, :74:20, :75:25
  assign _piso_io_wr = pixelDataReady & io_pixelData_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20, :107:46, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35
  PISO piso (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20
    .clock            (clock),
    .reset            (reset),
    .io_rd            (_piso_io_rd),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20
    .io_wr            (_piso_io_wr),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20
    .io_isEmpty       (_piso_io_isEmpty),
    .io_isAlmostEmpty (_piso_io_isAlmostEmpty),
    .io_din_0         (io_pixelData_bits_0),
    .io_din_1         (io_pixelData_bits_1),
    .io_din_2         (io_pixelData_bits_2),
    .io_din_3         (io_pixelData_bits_3),
    .io_din_4         (io_pixelData_bits_4),
    .io_din_5         (io_pixelData_bits_5),
    .io_din_6         (io_pixelData_bits_6),
    .io_din_7         (io_pixelData_bits_7),
    .io_din_8         (io_pixelData_bits_8),
    .io_din_9         (io_pixelData_bits_9),
    .io_din_10        (io_pixelData_bits_10),
    .io_din_11        (io_pixelData_bits_11),
    .io_din_12        (io_pixelData_bits_12),
    .io_din_13        (io_pixelData_bits_13),
    .io_din_14        (io_pixelData_bits_14),
    .io_din_15        (io_pixelData_bits_15),
    .io_dout          (_piso_io_dout)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:74:20
  assign io_busy = busyReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :70:24
  assign io_config_ready = configReady;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :103:30
  assign io_pixelData_ready = pixelDataReady;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :107:46
  assign io_frameBuffer_wr =
    io_enable & posReg_x <= {11'h0, 9'(io_video_regs_size_x - 9'h1)}
    & posReg_y <= {11'h0, 9'(io_video_regs_size_y - 9'h1)} & validReg & (|penReg_color);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:64:72, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/PaletteEntry.scala:63:35, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :88:25, :92:25, :93:27, :96:{64,76}, :115:34, :184:{37,44,79}
  assign io_frameBuffer_addr =
    configReg_hFlip
      ? 17'({8'(8'(io_video_regs_size_y[7:0] - posReg_y[7:0]) - 8'h1), 9'h0}
            + 17'(17'({8'h0, io_video_regs_size_x} - posReg_x[16:0]) - 17'h1))
      : 17'({posReg_y[7:0], 9'h0} + posReg_x[16:0]);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :71:28, :88:25, :144:39, :168:{21,29}, :169:{21,29}, :170:8, :171:58, :172:57
  assign io_frameBuffer_din = {penReg_priority, penReg_palette, penReg_color};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteBlitter.scala:53:7, :92:25, :118:32
endmodule

