// Generated by CIRCT firtool-1.135.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SpriteProcessor(	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
  input          clock,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
  input          reset,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
  input          io_ctrl_enable,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input  [1:0]   io_ctrl_format,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input          io_ctrl_start,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input          io_ctrl_zoom,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input  [1:0]   io_ctrl_regs_bank,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input          io_ctrl_regs_fixed,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input          io_ctrl_regs_hFlip,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  output         io_ctrl_vram_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  output [11:0]  io_ctrl_vram_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input  [127:0] io_ctrl_vram_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  output         io_ctrl_tileRom_rd,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  output [31:0]  io_ctrl_tileRom_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input  [63:0]  io_ctrl_tileRom_dout,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input          io_ctrl_tileRom_wait_n,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input          io_ctrl_tileRom_valid,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  output [7:0]   io_ctrl_tileRom_burstLength,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input          io_ctrl_tileRom_burstDone,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input  [8:0]   io_video_regs_size_x,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input  [8:0]   io_video_regs_size_y,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  output         io_frameBuffer_wr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  output [16:0]  io_frameBuffer_addr,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  output [15:0]  io_frameBuffer_din,	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
  input          io_frameBuffer_wait_n	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:47:14
);

  wire        _blitter_io_config_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire        _blitter_io_pixelData_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_4;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_5;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_7;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_8;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_9;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_10;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_11;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_12;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_13;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_14;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire [7:0]  _blitter_io_pixelData_bits_15;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire        _blitter_io_busy;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire        _blitter_io_config_ready;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire        _blitter_io_pixelData_ready;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  wire        _fifo_io_deq_ready;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
  wire        _fifo_io_flush;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
  wire        _fifo_io_deq_valid;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
  wire [63:0] _fifo_io_deq_bits;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
  wire [6:0]  _fifo_io_count;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
  reg  [2:0]  stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:82:25
  reg  [1:0]  spriteReg_priority;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg  [5:0]  spriteReg_colorCode;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg  [17:0] spriteReg_code;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg         spriteReg_hFlip;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg         spriteReg_vFlip;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg  [17:0] spriteReg_pos_x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg  [17:0] spriteReg_pos_y;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg  [7:0]  spriteReg_cols;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg  [7:0]  spriteReg_rows;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg  [15:0] spriteReg_zoom_x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg  [15:0] spriteReg_zoom_y;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
  reg  [15:0] numTilesReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:84:30
  reg         readPendingReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:85:31
  wire        _io_debug_next_T = stateReg == 3'h6;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:82:25, :88:80
  reg  [9:0]  spriteCounter;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
  reg  [15:0] tileCounter;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22
  wire        wrap_wrap_1 =
    tileCounter == 16'(numTilesReg - 16'h1) | numTilesReg == 16'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, :69:{22,29,35,41}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:84:30
  wire        tileRomRead = stateReg == 3'h5 & ~readPendingReg & _fifo_io_count < 7'h21;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :85:31, :92:20, :107:{30,48}, :108:{5,21}, :109:19
  wire        effectiveRead = tileRomRead & io_ctrl_tileRom_wait_n;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:107:48, :108:21, :112:32
  wire [3:0]  _tileRomAddr_T_2 = (&io_ctrl_format) ? 4'h8 : 4'h7;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:73:31, :119:58
  wire [32:0] tileRomAddr =
    {15'h0, 18'(spriteReg_code + {2'h0, tileCounter})} << _tileRomAddr_T_2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28, :119:{37,52,58}
  wire [5:0]  tileRomBurstLength = (&io_ctrl_format) ? 6'h20 : 6'h10;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:73:31, :109:19, :122:31
  reg  [2:0]  casez_tmp;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:150:20, :153:27
  always @(*) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:46, :84:73, :88:80, :93:26, :107:30, :132:17, :150:20, :153:27, :157:31, :160:32, :163:32, :167:37, :172:29, :177:16
    casez (stateReg)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:82:25, :83:46, :84:73, :88:80, :93:26, :107:30, :132:17, :150:20, :153:27, :157:31, :160:32, :163:32, :167:37, :172:29, :177:16
      3'b000:
        casez_tmp = io_ctrl_start ? 3'h1 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:46, :84:73, :88:80, :93:26, :107:30, :132:17, :150:20, :153:{27,38}, :157:31, :160:32, :163:32, :167:37, :172:29, :177:16
      3'b001:
        casez_tmp = 3'h2;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :83:46, :84:73, :88:80, :93:26, :107:30, :132:17, :150:20, :153:27, :157:31, :160:32, :163:32, :167:37, :172:29, :177:16
      3'b010:
        casez_tmp = 3'h3;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :83:46, :84:73, :88:80, :93:26, :107:30, :132:17, :150:20, :153:27, :157:31, :160:32, :163:32, :167:37, :172:29, :177:16
      3'b011:
        casez_tmp = {1'h1, ~((|spriteReg_cols) & (|spriteReg_rows)), 1'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:65:{30,38,46}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:{28,46}, :84:73, :88:80, :93:26, :107:30, :132:17, :150:20, :153:27, :157:31, :160:32, :163:{32,38}, :167:37, :172:29, :177:16
      3'b100:
        casez_tmp = _blitter_io_config_ready ? 3'h5 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:46, :84:73, :88:80, :93:26, :96:23, :107:30, :132:17, :150:20, :153:27, :157:31, :160:32, :163:32, :167:{37,48}, :172:29, :177:16
      3'b101:
        casez_tmp = effectiveRead & wrap_wrap_1 ? 3'h6 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:69:35, :92:24, :93:{48,55}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:82:25, :83:46, :84:73, :88:80, :93:26, :107:30, :112:32, :132:17, :150:20, :153:27, :157:31, :160:32, :163:32, :167:37, :172:{29,40}, :177:16
      3'b110:
        casez_tmp = _io_debug_next_T & (&spriteCounter) ? 3'h7 : 3'h1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, :45:24, :85:24, :86:{48,55}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :83:46, :84:73, :88:80, :93:26, :107:30, :119:58, :132:17, :150:20, :153:27, :157:31, :160:32, :163:32, :167:37, :172:29, :177:{16,22}
      default:
        casez_tmp = (&stateReg) & ~_blitter_io_busy ? 3'h0 : stateReg;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:46, :84:73, :88:80, :93:26, :96:23, :107:30, :132:17, :150:20, :153:27, :157:31, :160:32, :163:32, :167:37, :172:29, :177:16, :182:{12,30,41}
    endcase	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:82:25, :83:46, :84:73, :88:80, :93:26, :107:30, :132:17, :150:20, :153:27, :157:31, :160:32, :163:32, :167:37, :172:29, :177:16
  end // always @(*)
  wire [17:0] sprite_sprite_1_pos_x =
    io_ctrl_regs_fixed
      ? {io_ctrl_vram_dout[47:32], 2'h0}
      : {io_ctrl_vram_dout[41:32], 8'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:178:73, :180:13, :181:{12,19}
  wire [17:0] sprite_sprite_pos_x =
    io_ctrl_regs_fixed ? {io_ctrl_vram_dout[15:0], 2'h0} : {io_ctrl_vram_dout[9:0], 8'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:178:73, :180:13, :181:{12,19}
  wire [17:0] sprite_sprite_1_pos_y =
    io_ctrl_regs_fixed
      ? {io_ctrl_vram_dout[63:48], 2'h0}
      : {io_ctrl_vram_dout[57:48], 8'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:178:73, :180:28, :181:{19,33,40}
  wire [17:0] sprite_sprite_pos_y =
    io_ctrl_regs_fixed
      ? {io_ctrl_vram_dout[31:16], 2'h0}
      : {io_ctrl_vram_dout[25:16], 8'h0};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:178:73, :180:28, :181:{19,33,40}
  always @(posedge clock) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
    if (reset) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
      stateReg <= 3'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25
      readPendingReg <= 1'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:85:31
      spriteCounter <= 10'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34
      tileCounter <= 16'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22
    end
    else begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
      stateReg <= casez_tmp;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:82:25, :150:20, :153:27
      readPendingReg <= ~io_ctrl_tileRom_burstDone & (effectiveRead | readPendingReg);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:85:31, :112:32, :125:35, :126:20, :127:29, :128:20
      if (_io_debug_next_T)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:88:80
        spriteCounter <= 10'(spriteCounter + 10'h1);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, :46:22
      if (effectiveRead)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:112:32
        tileCounter <= wrap_wrap_1 ? 16'h0 : 16'(tileCounter + 16'h1);	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, :69:{29,35}, :70:{11,20}, :71:{16,24}
    end
    if (stateReg == 3'h2) begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:46
      spriteReg_priority <=
        io_ctrl_zoom ? io_ctrl_vram_dout[37:36] : io_ctrl_vram_dout[5:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, :120:32, :157:32, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_colorCode <=
        io_ctrl_zoom ? io_ctrl_vram_dout[45:40] : io_ctrl_vram_dout[13:8];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, :121:33, :158:33, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_code <=
        io_ctrl_zoom
          ? {io_ctrl_vram_dout[33:32], io_ctrl_vram_dout[63:48]}
          : {io_ctrl_vram_dout[1:0], io_ctrl_vram_dout[31:16]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, :122:{28,35}, :159:{28,35}, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_hFlip <= io_ctrl_zoom ? io_ctrl_vram_dout[35] : io_ctrl_vram_dout[3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, :123:29, :160:29, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_vFlip <= io_ctrl_zoom ? io_ctrl_vram_dout[34] : io_ctrl_vram_dout[2];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, :124:29, :161:29, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_pos_x <= io_ctrl_zoom ? sprite_sprite_pos_x : sprite_sprite_1_pos_x;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, :178:73, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_pos_y <= io_ctrl_zoom ? sprite_sprite_pos_y : sprite_sprite_1_pos_y;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, :178:73, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_cols <=
        io_ctrl_zoom ? io_ctrl_vram_dout[111:104] : io_ctrl_vram_dout[79:72];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, :126:28, :163:28, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_rows <=
        io_ctrl_zoom ? io_ctrl_vram_dout[103:96] : io_ctrl_vram_dout[71:64];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, :127:28, :164:28, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_zoom_x <= io_ctrl_zoom ? io_ctrl_vram_dout[79:64] : 16'h100;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
      spriteReg_zoom_y <= io_ctrl_zoom ? io_ctrl_vram_dout[95:80] : 16'h100;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/Util.scala:104:11, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:94:8, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    end
    if (stateReg == 3'h3)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :84:73
      numTilesReg <= 16'({8'h0, spriteReg_cols} * {8'h0, spriteReg_rows});	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/Sprite.scala:181:19, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28, :84:{30,46}
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
    `ifdef FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
      `FIRRTL_BEFORE_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
    initial begin	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
      `ifdef INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
        `INIT_RANDOM_PROLOG_	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
        for (logic [2:0] i = 3'h0; i < 3'h5; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
        end	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
        stateReg = _RANDOM[3'h0][2:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25
        spriteReg_priority = _RANDOM[3'h0][4:3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:28
        spriteReg_colorCode = _RANDOM[3'h0][10:5];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:28
        spriteReg_code = _RANDOM[3'h0][28:11];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:28
        spriteReg_hFlip = _RANDOM[3'h0][29];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:28
        spriteReg_vFlip = _RANDOM[3'h0][30];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:28
        spriteReg_pos_x = {_RANDOM[3'h0][31], _RANDOM[3'h1][16:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :83:28
        spriteReg_pos_y = {_RANDOM[3'h1][31:17], _RANDOM[3'h2][2:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :83:28
        spriteReg_cols = _RANDOM[3'h2][10:3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :83:28
        spriteReg_rows = _RANDOM[3'h2][18:11];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :83:28
        spriteReg_zoom_x = {_RANDOM[3'h2][31:19], _RANDOM[3'h3][2:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :83:28
        spriteReg_zoom_y = _RANDOM[3'h3][18:3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :83:28
        numTilesReg = {_RANDOM[3'h3][31:19], _RANDOM[3'h4][2:0]};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :83:28, :84:30
        readPendingReg = _RANDOM[3'h4][3];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :84:30, :85:31
        spriteCounter = _RANDOM[3'h4][13:4];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :84:30
        tileCounter = _RANDOM[3'h4][29:14];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:65:22, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :84:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
      `FIRRTL_AFTER_INITIAL	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign _fifo_io_flush = stateReg == 3'h0;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :92:20, :93:26
  Queue64_UInt fifo (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
    .clock        (clock),
    .reset        (reset),
    .io_enq_valid (io_ctrl_tileRom_valid),
    .io_enq_bits  (io_ctrl_tileRom_dout),
    .io_deq_ready (_fifo_io_deq_ready),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
    .io_deq_valid (_fifo_io_deq_valid),
    .io_deq_bits  (_fifo_io_deq_bits),
    .io_count     (_fifo_io_count),
    .io_flush     (_fifo_io_flush)	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
  assign _blitter_io_config_valid = stateReg == 3'h4;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :96:23, :132:17
  SpriteBlitter blitter (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .clock                           (clock),
    .reset                           (reset),
    .io_enable                       (io_ctrl_enable),
    .io_busy                         (_blitter_io_busy),
    .io_config_ready                 (_blitter_io_config_ready),
    .io_config_valid                 (_blitter_io_config_valid),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_config_bits_sprite_priority  (spriteReg_priority),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_sprite_colorCode (spriteReg_colorCode),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_sprite_hFlip     (spriteReg_hFlip),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_sprite_vFlip     (spriteReg_vFlip),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_sprite_pos_x     (spriteReg_pos_x),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_sprite_pos_y     (spriteReg_pos_y),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_sprite_cols      (spriteReg_cols),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_sprite_rows      (spriteReg_rows),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_sprite_zoom_x    (spriteReg_zoom_x),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_sprite_zoom_y    (spriteReg_zoom_y),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:83:28
    .io_config_bits_hFlip            (io_ctrl_regs_hFlip),
    .io_video_regs_size_x            (io_video_regs_size_x),
    .io_video_regs_size_y            (io_video_regs_size_y),
    .io_pixelData_ready              (_blitter_io_pixelData_ready),
    .io_pixelData_valid              (_blitter_io_pixelData_valid),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_0             (_blitter_io_pixelData_bits_0),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_1             (_blitter_io_pixelData_bits_1),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_2             (_blitter_io_pixelData_bits_2),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_3             (_blitter_io_pixelData_bits_3),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_4             (_blitter_io_pixelData_bits_4),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_5             (_blitter_io_pixelData_bits_5),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_6             (_blitter_io_pixelData_bits_6),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_7             (_blitter_io_pixelData_bits_7),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_8             (_blitter_io_pixelData_bits_8),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_9             (_blitter_io_pixelData_bits_9),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_10            (_blitter_io_pixelData_bits_10),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_11            (_blitter_io_pixelData_bits_11),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_12            (_blitter_io_pixelData_bits_12),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_13            (_blitter_io_pixelData_bits_13),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_14            (_blitter_io_pixelData_bits_14),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_bits_15            (_blitter_io_pixelData_bits_15),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_frameBuffer_wr               (io_frameBuffer_wr),
    .io_frameBuffer_addr             (io_frameBuffer_addr),
    .io_frameBuffer_din              (io_frameBuffer_din),
    .io_frameBuffer_wait_n           (io_frameBuffer_wait_n)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
  SpriteDecoder decoder (	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:101:23
    .clock                (clock),
    .reset                (reset),
    .io_format            (io_ctrl_format),
    .io_tileRom_ready     (_fifo_io_deq_ready),
    .io_tileRom_valid     (_fifo_io_deq_valid),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
    .io_tileRom_bits      (_fifo_io_deq_bits),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:92:20
    .io_pixelData_ready   (_blitter_io_pixelData_ready),	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:96:23
    .io_pixelData_valid   (_blitter_io_pixelData_valid),
    .io_pixelData_bits_0  (_blitter_io_pixelData_bits_0),
    .io_pixelData_bits_1  (_blitter_io_pixelData_bits_1),
    .io_pixelData_bits_2  (_blitter_io_pixelData_bits_2),
    .io_pixelData_bits_3  (_blitter_io_pixelData_bits_3),
    .io_pixelData_bits_4  (_blitter_io_pixelData_bits_4),
    .io_pixelData_bits_5  (_blitter_io_pixelData_bits_5),
    .io_pixelData_bits_6  (_blitter_io_pixelData_bits_6),
    .io_pixelData_bits_7  (_blitter_io_pixelData_bits_7),
    .io_pixelData_bits_8  (_blitter_io_pixelData_bits_8),
    .io_pixelData_bits_9  (_blitter_io_pixelData_bits_9),
    .io_pixelData_bits_10 (_blitter_io_pixelData_bits_10),
    .io_pixelData_bits_11 (_blitter_io_pixelData_bits_11),
    .io_pixelData_bits_12 (_blitter_io_pixelData_bits_12),
    .io_pixelData_bits_13 (_blitter_io_pixelData_bits_13),
    .io_pixelData_bits_14 (_blitter_io_pixelData_bits_14),
    .io_pixelData_bits_15 (_blitter_io_pixelData_bits_15)
  );	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:101:23
  assign io_ctrl_vram_rd = stateReg == 3'h1;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :82:25, :188:31
  assign io_ctrl_vram_addr = {io_ctrl_regs_bank, spriteCounter};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/arcadia/src/util/Counter.scala:40:34, home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :116:41
  assign io_ctrl_tileRom_rd = tileRomRead;	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :107:48, :108:21
  assign io_ctrl_tileRom_addr = tileRomAddr[31:0];	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :119:52, :191:24
  assign io_ctrl_tileRom_burstLength = {2'h0, tileRomBurstLength};	// home/se/repos/github.com/MiSTer-devel/Arcade-Cave_MiSTer/cave/src/gfx/SpriteProcessor.scala:46:7, :122:31, :192:31
endmodule

